### ISSUE TITLE
[input] Gamepad buttons and axis not working (linux)

### ISSUE THREAD

**Issue by muevoid** [raysan5/raylib#1319] opened 2020-07-22 06:54 UTC
### Issue description

I have tried in both my own project and the gamepad example both in browser and
on my machine compiled. However it just shows up with gamepad not detected.
I have tested with jstest to make sure the joystick is showing up on a system
level and it appears to be fine. (To note i have tried this with both a Xbox
one controller and a steam controller)

### Environment

I am on KISS Linux latest stable kernel.

### Code Example

Just the code in the gamepad_test_example that checks if a gamepad is
available. AKA (IsGamePadAvailable(GAMEPAD_PLAYER1))

**Comment by raysan5** [comment] 2020-07-25 18:18
@muevoid is the gamepad connected before running the example? It should be at least detected... it could be a KISS Linux specific issue...

**Comment by muevoid** [comment] 2020-07-25 18:24
Yes i can confirm the gamepad is connected before hand. I'm not sure exactly what on KISS could cause this issue.

**Comment by raysan5** [comment] 2020-07-25 18:42
@muevoid raylib uses GLFW internally on DESKTOP_PLATFORM (Windows, Linux, macOS) to manage inputs. Every frame [core] `PollInputEvents()` is called that also scans possible gamepads with `glfwJoystickPresent()`.

`IsGamepadAvailable(int gamepad)` just returns the result of that detection (`true` or `false`), you can try with different `int gamepad` values just in case but if the function always returns `false` then the issue is probably on GLFW side and not in raylib.

**Comment by muevoid** [comment] 2020-07-25 18:43
Kk I am familiar with glfw and will test this tommorow.

**Comment by raysan5** [comment] 2020-07-25 18:48
Just a reference in case it can be useful in the future for gamepad buttons mapping: https://www.glfw.org/docs/3.3/input_guide.html#gamepad

**Comment by defutura** [comment] 2020-08-10 21:32
An additional perspective > I just tried this on Ubuntu 20.04 LTS x86_64, kernel: 5.4.0-42-generic. My build of 'core_input_gamepad.c' detects both a cheap Logitech controller and an 8bitdo SNES controller. They do not need to be plugged in before compilation; I can disconnect and reconnect the controllers, and the program will detect them and display their names correctly. However, I can't seem to be able to get any input from any of them, and neither buttons nor axes show up in the interface.

**Comment by muevoid** [comment] 2020-08-10 21:33
Hmmm I am still doing testing will post here soon.

**Comment by muevoid** [comment] 2020-08-11 04:42
This is for sure an issue with my configuration and not raylib. So I will close this jist of it was my Xorg configuration and some stuff with evdev.

**Comment by muevoid** [comment] 2020-08-11 07:26
I may have talked too soon my issue is now identical to defuturas. Gamepad is detected by raylib however no buttons or axis is detected.

**Comment by defutura** [comment] 2020-08-11 13:07
> neither buttons nor axes show up in the interface.

I should have expressed myself more clearly here. The program does in fact detect the 5 axes correctly with GetGamepadAxisCount() on line 179, and displays them with the following for loop, but no input data is shown for any of them.

**Comment by muevoid** [comment] 2020-09-02 00:07
@defutura Have you had any luck with this yet?

**Comment by defutura** [comment] 2020-09-05 14:57
@muevoid No, I haven't looked at it yet, I'm doing most of my programming on a Windows machine. Will post here if I find anything out.

**Comment by coderoth** [comment] 2020-09-16 19:48
@defutura, I had the same problem today. Raylib identified my gamepad and correctly detected connections/disconnections, but couldn identify button presses and axis movements.

My joystick worked fine with SDL and glfw3 sample codes, but not with raylib.
My case was that the glfw gamepad database mapping was not updated with my model (03000000c62400003a54000001010000).

I've found a mapping for my gamepad here:
https://github.com/gabomdq/SDL_GameControllerDB/

With the mapping configuration for my gamepad, I cloned the raylib repo and added the mapping in the folder <RAYLIB_HOME>/src/external/glfw/src/mappings.h and then recompiled the whole thing again.

After this it all worked.

**Comment by raysan5** [comment] 2020-09-18 00:24
@coderoth thank you very much for reporting! 

Please, could you check if [GLFW3](https://github.com/glfw/glfw) main branch is also updated? I will update raylib glfw version with it...

**Comment by coderoth** [comment] 2020-09-18 03:54
My gamepad ID is not in their repository [mappings.h](https://github.com/glfw/glfw/blob/master/src/mappings.h) list (03000000c62400003a54000001010000).

They have a Cmake script that "updates" the mappings.h file with the latest gamecontrollerdb.txt file:
https://github.com/glfw/glfw/blob/master/CMake/GenerateMappings.cmake

It seems the repository mappings.h is outdated (was updated 10 months ago and it has 476 lines, while the gamecontrollerdb.txt has more than 800). One weird thing is that my controller id was added to the gamecontrollerdb.txt 2 years ago (03000000c62400003a54000001010000), but it is not in the glfw mappings.h file...

Maybe they manually execute that cmake script as part of the build?

I cloned their repository and issued the following commands to update the mappings and it worked (the final mappings file went from 476 lines to 954 and my gamepad id was updated):

cd CMake
cmake -P GenerateMappings.cmake ../src/mappings.h.in ../src/mappings.h

**Comment by raysan5** [comment] 2020-09-19 17:32
@coderoth I maintain the plain Makefiles building system, not the CMake... maybe I can just update `mappings.h` manually on raylib side. Could you provide the updated file, please?

**Comment by coderoth** [comment] 2020-09-19 18:25
Updated version of the file:
[mappings.h.txt](https://github.com/raysan5/raylib/files/5250343/mappings.h.txt)

Created the following pull request, if you prefer:
https://github.com/raysan5/raylib/pull/1381

**Comment by raysan5** [comment] 2020-09-25 15:45
Updated! It should work now! Closing the issue!

**Closed by raysan5** 2020-09-25 15:45 UTC
