### ISSUE TITLE
[build] Yet another issue with Makefile and the documentation

### ISSUE THREAD

**Issue by vbarboza** [raysan5/raylib#472] opened 2018-02-17 01:32 UTC
Please, correct me if I'm wrong opening this issue as I have seen already issues #332, #336 and #401 dealing with different approaches (build on Linux, cmake and packaging). I've also read somewhere we are not deprecating the Makefile and changing the dependencies on openAL and GLFW, so here is my problem.

Yesterday I started reading the docs (https://github.com/raysan5/raylib/wiki/Compile-for-GNU-Linux) and building on my Linux Mint 18 (Ubuntu 16.04 LTS for all the matters), x86_64. The raylib compiles alright, but the `examples/` and `games/` don't.

In `examples/` I had to allow multiple function definitions or it wouldn't compile: ` -Wl,-allow-multiple-definition`, install libopenal-dev and add it to the `LDLIBS`.

In `games/` I had to change the `-lglfw3` to `-lglfw` as I read somewhere around the mentioned issues (but I missed comments or documentation regarding this, so I'm opening this). My solution added a `GLFW_LIBTYPE` which I'm not sure is the best way to go.

My changes were commited to my fork (https://github.com/vbarboza/raylib/tree/develop) - not sure if a PR is appropriate.

**Comment by a3f** [comment] 2018-02-17 01:39
Could you paste the link errors?

**Comment by RDR8** [comment] 2018-02-17 04:09
The issue with GLFW3 is because it builds with those different linker names depending upon if it was built as static or shared. The wiki instructions to build GLFW3 result in a static library and that is what the Makefile is looking for by default. If you have installed GLFW3 with your package manager, it is the shared variety. I don't know if you have any recourse except for changing the name manually as you have. I think it's been reported upstream to GLFW3 but I don't know if any changes were, or will be, made. Thanks for your input.

**Comment by vbarboza** [comment] 2018-02-20 01:35
Thanks for your replies. I started a clean installation and got stuck with the same issues.

- First, the `examples/`:

`$ make PLATFORM=PLATFORM_DESKTOP`

> gcc -o core/core_basic_window core/core_basic_window.c -O1 -s -Wall -std=c99 -D_DEFAULT_SOURCE -fgnu89-inline -Wno-missing-braces -no-pie -D_DEFAULT_SOURCE -I. -I/usr/local/include/raysan5 -I../release/include -I../src -I../src/external -L. -L/usr/local/lib/raysan5 -L../release/libs/linux -L../src -lraylib -lGL -lm -lpthread -ldl -lrt -lX11 -DPLATFORM_DESKTOP
> /usr/local/lib/raysan5/libraylib.a(textures.o): In function 'stb_perlin_noise3':
> textures.c:(.text+0x69cc): multiple definition of 'stb_perlin_noise3'
> /usr/local/lib/raysan5/libraylib.a(textures.c.o):textures.c:(.text+0xf6): first defined here
> /usr/local/lib/raysan5/libraylib.a(textures.o): In function 'stb_perlin_ridge_noise3':
> textures.c:(.text+0x6d69): multiple definition of 'stb_perlin_ridge_noise3'
> ...

My solution was adding `-Wl,-allow-multiple-definition` to the Makefile, which doesn't seem right to me.

- Then, I had the openAL problem:

> /usr/local/lib/raysan5/libraylib.a(audio.c.o): In function `InitAudioDevice':
> audio.c:(.text+0x9714): undefined reference to `alcOpenDevice'
> audio.c:(.text+0x974b): undefined reference to `alcCreateContext'
> ...
> Makefile:395: recipe for target 'audio/audio_sound_loading' failed
> make: *** [audio/audio_sound_loading] Error 1

And my solution was adding the `-lopenal` to the Makefile.

- Finally, in `games/` the -lglfw3 issue.

@RDR8 The GLFW_LIBTYPE would be in fact a switch and using USE_EXTERNAL_GLFW isn't working for me (I should double check it and the Makefile). And in fact, I followed the Wiki instructions to link raylib with system GLFW (which is a shared lib due to `-DBUILD_SHARED_LIBS=ON`, correct?).

**Comment by RDR8** [comment] 2018-02-20 02:06
> My solution was adding -Wl,-allow-multiple-definition to the Makefile, which doesn't seem right to me.  

@a3f I wonder if this has anything to do with raylib.h differing in raylib/src and raylib/release/include?  

@vbarboza I see. I have not done anything with an external, compiled static or packaged shared, GLFW since raysan5 started bundling it. As far as I know, `-DBUILD_SHARED_LIBS=ON` in src/Makefile is just referring to libraylib.so. I'm passing RAYLIB_LIBTYPE=SHARED from the prompt to all the targets as needed in src/Makefile and building the examples with it too.

**Comment by vbarboza** [comment] 2018-02-21 01:04
>  I'll review the docs and usage of the default static build target and USE_EXTERNAL_GLFW when I get a chance. Holler back if you figure it out.

@RDR8 

Today I checked the `games/Makefile` and it doesn't check fot the `USE_EXTERNAL_GLFW` compilation option as the other Makefiles, passing -lglfw3 when building for Linux.

@a3f 
Regarding the multiple defitions, as I am not familiar with the library architecture, no clue on the issue.

**Comment by RDR8** [comment] 2018-02-21 02:57
@vbarboza Tracking down the multiple defs, Do you have raylib installed with `make install`? If so, gcc may be looking at two versions of raylib.h. Try removing -I$(RAYLIB_PATH)/release/includes temporarily from INCLUDE_PATHS at about examples/Makefile:226 or 248. If the problem goes away, hmm.. well better lucky than good. RAYLIB_H_INSTALL_PATH is the location where raylib.h is placed by `make install ...` If you remove that from INCLUDE_PATHS instead, and get the same error, maybe the problem is due to the difference between the newer src/raylib.h and older release/include/raylib.h. The "installed" version is a copy of src/raylib.h since it's newer and what we build against. release/include/raylib.h is provided, I think, for the binaries that come with raylib. I'm not sure why it's not been updated. 

I haven't looked over games/ or templates/ makefiles in a while. I am working on extending and documenting the install : target and usage of the examples. If that works out well, I'll try to push the _PATHs out to the other makefiles. I still don't really know the ins and outs of your use case.

**Comment by RDR8** [comment] 2018-02-22 03:10
I saw 
 `/usr/local/lib/raysan5/libraylib.a(textures.o): In function 'stb_perlin_noise3':
textures.c:(.text+0x69cc): multiple definition of 'stb_perlin_noise3'
/usr/local/lib/raysan5/libraylib.a(textures.c.o):textures.c:(.text+0xf6): first defined here
/usr/local/lib/raysan5/libraylib.a(textures.o): In function 'stb_perlin_ridge_noise3':
textures.c:(.text+0x6d69): multiple definition of 'stb_perlin_ridge_noise3'`

briefly, but it went away using the provided libraylib.a in ../release/libs/linux before `make clean` or after `git checkout ../release/libs/linux/libraylib.a`. It also seems to be working after `make install`.
I am using the makefiles staged at #480 .

**Comment by raysan5** [comment] 2018-04-02 16:46
It should work ok now. Just closing this issue. Feel free to reopen it if problem persists.

**Closed by raysan5** 2018-04-02 16:46 UTC
