### ISSUE TITLE
[core] Mac display rectangle size. bug

### ISSUE THREAD

**Issue by geofl** [raysan5/raylib#1583] opened 2021-02-11 22:40 UTC
I have been playing around the examples, I tried to apply the post-processing sample code on another example I have been working on and realized that the texture that the post-processing effects are rendered on is 1/4th of the actual screen size. 

After @JeffM2501 instructions I tried using DrawTexturePro, which gave the exact results, after hacking it a bit and doubling the sizes it produced the expected results.

Before with both methods and normal screen sizes.
<img width="1591" alt="Screenshot 2021-02-11 at 22 37 59" src="https://user-images.githubusercontent.com/1167580/107707489-da2c0680-6cb9-11eb-800b-4a3d5fa0b750.png">

After doubling the dest rect sizes in DrawTexturePro
<img width="1598" alt="Screenshot 2021-02-11 at 22 39 17" src="https://user-images.githubusercontent.com/1167580/107707586-ff207980-6cb9-11eb-99b9-2624a85ad7a1.png">

raylib -> 3.5 version
system info -> MacBook Pro (16-inch, 2019), i7, AMD Radeon Pro 5500M 8 GB
code -> https://gist.github.com/geofl/92ae036a79e7a4de5172ffbadf0b6d5c

**Comment by raysan5** [comment] 2021-02-12 12:27
Please, could you confirm this issue is not a duplicate of #1510 and #1086?

**Closed** 2021-02-12 12:31 UTC
