### ISSUE TITLE
[build] Error when building examples

### ISSUE THREAD

**Issue by gavriil07** [raysan5/raylib#792] opened 2019-04-06 20:03 UTC
I use mingw and CLion to run the examples. 

```
In file included from c:\mingw\include\windows.h:48,
                 from D:\raylib-master\raylib-master\src\external/miniaudio.h:3034,
                 from D:\raylib-master\raylib-master\src\raudio.c:82:
c:\mingw\include\winuser.h:3519:25: error: conflicting types for 'CloseWindow'
 WINUSERAPI BOOL  WINAPI CloseWindow (HWND);
                         ^~~~~~~~~~~
In file included from D:\raylib-master\raylib-master\src\raudio.c:72:
D:\raylib-master\raylib-master\src\raylib.h:897:12: note: previous declaration of 'CloseWindow' was here
 RLAPI void CloseWindow(void);                                     // Close window and unload OpenGL context
            ^~~~~~~~~~~
In file included from c:\mingw\include\windows.h:48,
                 from D:\raylib-master\raylib-master\src\external/miniaudio.h:3034,
                 from D:\raylib-master\raylib-master\src\raudio.c:82:
c:\mingw\include\winuser.h:4284:23: error: conflicting types for 'ShowCursor'
 WINUSERAPI int WINAPI ShowCursor (BOOL);
                       ^~~~~~~~~~
In file included from D:\raylib-master\raylib-master\src\raudio.c:72:
D:\raylib-master\raylib-master\src\raylib.h:924:12: note: previous declaration of 'ShowCursor' was here
 RLAPI void ShowCursor(void);                                      // Shows cursor
            ^~~~~~~~~~
In file included from D:\raylib-master\raylib-master\src\raudio.c:72:
D:\raylib-master\raylib-master\src\raylib.h:142:21: error: conflicting types for 'UnhideWindow'
 #define ShowWindow  UnhideWindow
                     ^~~~~~~~~~~~
In file included from D:\raylib-master\raylib-master\src\raudio.c:72:
D:\raylib-master\raylib-master\src\raylib.h:903:12: note: previous declaration of 'UnhideWindow' was here
 RLAPI void UnhideWindow(void);                                    // Show the window
            ^~~~~~~~~~~~
```

**Comment by raysan5** [comment] 2019-04-07 21:37
It shouldn't happen. Are you building raylib as 64 bit?

**Comment by gavriil07** [comment] 2019-04-08 05:54
OS: windows 10
Version: master
compiler: mingw32

**Comment by raysan5** [comment] 2019-04-23 16:13
Try using mingw32-w64. It seems issue could also be CLion related. Closing it in the meantime, as continuous integration works.

**Closed by raysan5** 2019-04-23 16:13 UTC

**Comment by gavriil07** [comment] 2019-04-23 19:04
It works with mingw64, finally!! 🥇

**Comment by SzieberthAdam** [comment] 2020-03-02 22:45
Same issue for me when build raylib with make from command prompt.
win10, mingw32 32 bit.

I do not intend to install 64 bit mingw.

Note that Makefile L22 `CC ?= gcc` results `The system cannot find the file specified.` error. It works with `CC = gcc`.

**Comment by mjocean** [comment] 2020-04-28 13:00
If mingw32 is not supported, can I request that the web documentation be updated to reflect that mingw64 is required?  Also, it would be helpful to change the title of this issue to mingw64 is required on windows.  Thank you!

**Comment by wernsey** [comment] 2020-08-10 13:46
I came across this issue when trying to compile with Mingw32 using `cmake -G 'MSYS Makefiles' ..`

The problem is that `raudio.c` pulls in Win32's `windows.h` through `miniaudio.h`, causing the Win32 `CloseWindow` and `ShowCursor` definitions to conflict with the Raylib definitions of those functions.

I see that `raudio.c` has these lines before `#include <windows.h>` to get rid of the unwanted function definitions:

```c
// If defined, the following flags inhibit definition of the indicated items.
#define NOGDICAPMASKS     // CC_*, LC_*, PC_*, CP_*, TC_*, RC_
#define NOVIRTUALKEYCODES // VK_*
#define NOWINMESSAGES     // WM_*, EM_*, LB_*, CB_*
#define NOWINSTYLES       // WS_*, CS_*, ES_*, LBS_*, SBS_*, CBS_*
// ...
```

but Mingw32's `windows.h` and related headers does not do anything with these `#define`s. AFAICT this is why it compiles with Mingw64 but not with Mingw32.

It seems that the best way to get `raudio.c` compiled is to tell it to use the `raudio.h` standalone header, by putting this block right at the top of the file:

```c
#if defined(__MINGW32__) && !defined(__MINGW64__)
#  define RAUDIO_STANDALONE
#  define USING_MINGW32
void SaveFileData(const char *fileName, void *data, unsigned int bytesToWrite);
#endif
```
It tries to check whether it is being built with Mingw32 and not Mingw64 (based on [this answer](https://stackoverflow.com/a/17493828/115589)), and then declares `RAUDIO_STANDALONE` to use `raudio.h` rather than `raylib.h`. It seems that the function `SaveFileData` is referenced in `raudio.c` but not declared in `raudio.h`, so I also put a prototype in this block.

Then right at the bottom of the file you need to modify the block that creates the `IsFileExtension` function when `RAUDIO_STANDALONE` to not do it if `USING_MINGW32` is defined. The body of `SaveFileData` should probably go into this `#if` block as well, but I didn't go so far.

```c
// Some required functions for audio standalone module version
#if defined(RAUDIO_STANDALONE) && !defined(USING_MINGW32)
// Check file extension
bool IsFileExtension(const char *fileName, const char *ext)
{
    // ...snip...
}
#endif
```

Unfortunately, this only gets it compiled. With the exception of `audio_raw_stream.exe`, none of the audio examples actually seem to play sounds, and the logs don't provide any clues as to why. It doesn't crash or anything, there's just silence.

**Comment by terraKote** [comment] 2020-09-25 22:38
Still having this issue. Using raylib 3.0.0 (01 April 2020) with spdlog and having error "UnhideWindow can't override function with C binding" (C2733) at Visual Studio Community 2019, 16.6.1,

**Comment by chriscamacho** [comment] 2020-09-26 06:14
I've found much better results with window, when using the windows subsystem for linux

This does not encumber your exe with a dependency (other than possibly a single gcc dll which can be packaged with the exe (WSL does not do graphics or opengl or sound or anything else other than provide a build environment)

The Linux build tools when used in windows, give a much easier build environment, allowing the use of make and is generally a lot fraught with issues...

There are a number of misconceptions about using this build environment so I ended up blogging about it

http://bedroomcoders.co.uk/creating-a-64-bit-executable-with-raylib-on-windows/

alas I found I needed to blog again to clear up further misconceptions !

http://bedroomcoders.co.uk/looking-again-at-compiling-a-windows-raylib-app/

using mingw-32 to create a 32-bit windows exe - is using a compiler ported from another OS, rather easier just to run gcc from a WSL command prompt (bash!) using this method it is also possible to use the same cross compiler packages from Linux to create windows exes.... fantastic no need to boot the toyOS box !!

**Comment by jamesl-github** [comment] 2020-09-26 16:06
> Still having this issue. Using raylib 3.0.0 (01 April 2020) with spdlog and having error "UnhideWindow can't override function with C binding" (C2733) at Visual Studio Community 2019, 16.6.1,

what example are you trying to build ?

**Comment by terraKote** [comment] 2020-09-27 19:13
> > Still having this issue. Using raylib 3.0.0 (01 April 2020) with spdlog and having error "UnhideWindow can't override function with C binding" (C2733) at Visual Studio Community 2019, 16.6.1,
> 
> what example are you trying to build ?

I'm trying to build custom logging example. Here's my change:
```
#include "spdlog/spdlog.h"

// Custom logging funtion
void LogCustom(int msgType, const char* text, va_list args)
{
    switch (msgType)
    {
    case LOG_INFO:
        spdlog::info(TextFormat(text, args));
        break;
    default: break;
    }
}
```

**Comment by JSH32** [comment] 2023-07-01 19:46
Also having this currently

**Comment by orcmid** [comment] 2023-07-01 21:44
@JSH32 Can you be a bit more specific?  The latest release of raylib is 4.5.0.  Also, the @terraKote example is using a C++ namespace and probably other things that may have led to a conflict between C and C++ bindings.  Especially because `spdlog.h` is all C++ (nicer to name it `spdlog.hpp` for that reason).  

Are you also attempting to use a Visual Studio Community Edition?

**Comment by terraKote** [comment] 2023-07-18 20:14
Solution for my problem was using global namespaces. When you mix C and C++, you may encounter situations, that you use the names for methods. In this case, you can specify which method you want to use explicitly, by providing namespace. As a rule, the code from C++ has a namespace (but not always) and C code is stored in global namespace. You can read more about them here https://learn.microsoft.com/en-us/cpp/cpp/namespaces-cpp?view=msvc-170#the-global-namespace
