### ISSUE TITLE
[shapes] Pixel leaks when drawing two circles on top of each other with MSAA on

### ISSUE THREAD

**Issue by shiMusa** [raysan5/raylib#2410] opened 2022-03-25 15:26 UTC
### Issue description

Similar to [this closed issue](https://github.com/raysan5/raylib/issues/2286), pixel leaks occur when two circles are drawn on top of each other with `DrawCircleV` and MSAA on:
![image](https://user-images.githubusercontent.com/17574234/160149709-3799ae52-c638-45f9-a41f-83876bf2827b.png)
MSAA off
![image](https://user-images.githubusercontent.com/17574234/160149741-74625f19-2599-456b-8599-abdc0a7f5876.png)

Reproduced by @Peter0x44  on AMD:
![image](https://user-images.githubusercontent.com/17574234/160149984-cf43e842-e013-4f62-910a-8fa1986a1ee0.png)

### Environment

Win 11, Nvidia 
```
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 390
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce GTX 1080 Ti/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 512.15
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
```

### Code Example

```
#include "raylib.h"

int main(void)
{
    SetConfigFlags(FLAG_MSAA_4X_HINT);
    InitWindow(200, 200, "circle with holes");
    SetTargetFPS(60);

    while (!WindowShouldClose())
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawCircle(100, 100, 5.0f, GRAY);
            DrawCircle(100, 100, 5.0f, RED);
        EndDrawing();
    }

    CloseWindow();

    return 0;
}
```

**Comment by raysan5** [comment] 2022-03-25 15:32
@shiMusa I'm afraid this issue is out-of-scope of raylib. I think it could be related to the way triangles are processed and how MSAA softens the junctions between triangles but trying to solve this issue will probably require a big redesign of the library.

If anyone else finds this issue, feel free to investigate the cause and the possible solution.

**Comment by raysan5** [comment] 2022-03-25 16:24
It seams issue only happens when `DrawCircle()` uses `RL_QUADS` and not `RL_TRIANGLES`. It worth investigating it!

**Comment by raysan5** [comment] 2022-04-24 13:14
Reviewed the issue. `DrawCircle()` calls `DrawCircleSector()` that uses `RL_QUADS` as expected, drawing two segments per quad. I concluded the time and efford to review this issue is greater than the benefit it provides so I'm closing it.

**Closed by raysan5** 2022-04-24 13:14 UTC

**Comment by Peter0x44** [comment] 2022-04-24 13:20
OK, I agree
I think users who have this need can just use the RL_TRIANGLES implementation.

**Comment by JulianBohne** [comment] 2023-08-06 11:12
I also have this problem when drawing small circles with AA enabled, but I traced it back to the implementation of DrawCircleV:
`rshapes.c`
```c
// Draw a color-filled circle (Vector version)
// NOTE: On OpenGL 3.3 and ES2 we use QUADS to avoid drawing order issues
void DrawCircleV(Vector2 center, float radius, Color color)
{
    DrawCircleSector(center, radius, 0, 360, 36, color);
}
```

The circle segments are always set to 36 which is not an appropriate value for smaller circles. I rebuilt the library with a zero in that place and this way the current implementation of `DrawCircleSector` automatically calculates a proper segment count for the given radius. This also fixes the issue, that very large circles (e.g. 1000 pixel radius) drawn with `DrawCircle` aren't very smooth, because the segment count is always 36.

My code:
```c
#include <raylib.h>

int main(int argc, char** argv) {
    SetConfigFlags(FLAG_MSAA_4X_HINT);
    InitWindow(800, 600, "Yello :D");
    SetTargetFPS(60);

    while(!WindowShouldClose()) {
        BeginDrawing();
        ClearBackground(RAYWHITE);

        DrawCircle(300, 300, 10.0, BLUE); // Small circle
        // DrawCircle(1100, 300, 1000.0, BLUE); // Large circle

        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```
Before changes:
![Circle_with_leaks](https://github.com/raysan5/raylib/assets/57051885/2ecc696f-7878-402a-9580-c0f3e8421ca5)
![large_circle_before](https://github.com/raysan5/raylib/assets/57051885/3d9349f6-813a-483e-904f-d25964a9f2be)


My proposal would be to change the `DrawCircleV` function to the following:
`rshapes.c`
```c
// Draw a color-filled circle (Vector version)
// NOTE: On OpenGL 3.3 and ES2 we use QUADS to avoid drawing order issues
void DrawCircleV(Vector2 center, float radius, Color color)
{
    DrawCircleSector(center, radius, 0, 360, 0, color); // Zero indicates that DrawCircleSector calculates an appropriate value for the segment count
}
```

After changes:
![small_circle_after](https://github.com/raysan5/raylib/assets/57051885/18d879ff-1780-4f2f-9cb3-2efcf2a62280)
![Large_circle_after](https://github.com/raysan5/raylib/assets/57051885/e3aaf4bb-038f-4035-8a07-fae31a3e1afe)

One note: Something that I'm not happy with would be that the small circle is now rather jagged, but that can be fixed by defining `SMOOTH_CIRCLE_ERROR_RATE` to something like 0.25 when building the library.

Final result:
![small_circle_error_rate_changed](https://github.com/raysan5/raylib/assets/57051885/5e0edb12-f3a2-476b-b369-1dee2bc44900)
