### ISSUE TITLE
[build] CMake raylib not found

### ISSUE THREAD

**Issue by gavriil07** [raysan5/raylib#813] opened 2019-04-23 20:49 UTC
Another cmake problem sorry...
In the projects folder we have a cmake example:

```
cmake_minimum_required(VERSION 3.13)
project(Origo)

set(CMAKE_CXX_STANDARD 11)

find_package(raylib 2.0 QUIET) # Let CMake search for a raylib-config.cmake

#You could change the QUIET above to REQUIRED and remove this if() clause
#This part downloads raylib and builds it if it's not installed on your system
if (NOT raylib_FOUND) # If there's none, fetch and build raylib
    include(FetchContent)

    FetchContent_Declare(
            raylib
            URL https://github.com/raysan5/raylib/archive/master.tar.gz
    )

    FetchContent_GetProperties(raylib)
    if (NOT raylib_POPULATED) # Have we downloaded raylib yet?
        set(FETCHCONTENT_QUIET NO)
        FetchContent_Populate(raylib)

        set(BUILD_EXAMPLES OFF CACHE BOOL "" FORCE) # don't build the supplied examples
        set(BUILD_GAMES    OFF CACHE BOOL "" FORCE) # or games


        # build raylib
        add_subdirectory(${raylib_SOURCE_DIR} ${raylib_BINARY_DIR})
    endif()

endif()
```

I followed the advice and commented the part that fetches the library and it seems that find_package never finds raylib and the if() clause gets execute every single time..

**Comment by raysan5** [comment] 2019-04-28 14:08
This issue seems user-code related, current CMake building proves to work for most platforms throught the CI build system... but maybe @a3f has some idea about it?

**Comment by araducan** [comment] 2019-04-30 17:55
The issue is that the library is fetched every time, it works but not the intended way

**Comment by a3f** [comment] 2019-05-01 06:08
> Another cmake problem sorry...

No need to be sorry!

> the if() clause gets execute every single time..

The first if-clause will always execute if you haven't raylib installed systemwide.
It didn't cause any problems for me, when I just tried. I tried to reproduce with

```
cd projects/CMake
mkdir build
cd build
cmake ..
make
touch ../core_basic_window.c ../CMakeLists.txt
make
cmake ..
make
```

And raylib was only downloaded only a single time as expected. I am running cmake 3.13.4 on macOS and raylib isn't installed systemwide. What steps did you follow?

> The issue is that the library is fetched every time, it works but not the intended way

The `if (NOT raylib_POPULATED)` clause always succeeds in the sample project, because it's meant to protect against other cmake files depending on raylib, i.e. There are multiple `FetchContent_Populate(raylib)`, which might be the case with a bigger project. The first one to run will check if it had downloaded raylib before and set `raylib_POPULATED=True`. Did you observe anything else happening?

**Comment by raysan5** [comment] 2019-05-01 12:39
@a3f not sure if it could be related but I updated GLFW library to latest version some days ago and Travis CI shows two jobs broken:

 - Linux job is related to not using latest GLFW on DLL, so, HighDPI functionality is missing.
 - macOS job also seems related to not finding GLFW library (or not linking properly)

**Comment by a3f** [comment] 2019-05-04 19:48
@raysan5

* I haven't found a precompiled Debian package for GLFW 3.3 in a quick search. I guess the best thing would be to have CI build glfw 3.3 from scratch, if we want to test that configuration..

* I don't completely understand why it fails, but I think it's related to macOS deprecating 32-bit software. I guess, that's a configuration we shouldn't test anymore.

**Comment by a3f** [comment] 2019-05-04 21:13
> I haven't found a precompiled Debian package for GLFW 3.3 in a quick search. I guess the best thing would be to have CI build glfw 3.3 from scratch, if we want to test that configuration..

Travis CI now builds the GLFW we bundle and installs it when testing the external GLFW configuration.

> I don't completely understand why it fails, but I think it's related to macOS deprecating 32-bit software. I guess, that's a configuration we shouldn't test anymore.

It failed because two lines I had modified in the GLFW `CMakeLists.txt` were overwritten in the last GLFW update. I reinstated them in 36d8a648f0cbc9bff9893b4e7612846097e76397.

**Comment by a3f** [comment] 2019-05-04 21:14
Those are both unrelated to @gavriil07's issue though, so the question still stands: What steps did you follow?

**Comment by gavriil07** [comment] 2019-05-07 05:44
I followed the instructions. I made a build, then commented the part which fetched the library, plus changed QUIET to REQUIRED in find_package as stated, and I got the error on find_package that it could not find the library

**Comment by a3f** [comment] 2019-05-07 08:21
@gavriil07 Have you run `make install` in the CMake build directory?

`find_package` has a predefined search path with directories it searches. In order for raylib to be found, `raylib-config.cmake` must be copied to one of these directories, which is part of the install, not the build stage.

**Comment by raysan5** [comment] 2019-05-24 22:52
Closing the issue, feel free to reopen it if problem persists.

**Closed by raysan5** 2019-05-24 22:52 UTC
