### ISSUE TITLE
[examples] models_box_collision demo broken w/ OpenGL 1.x

### ISSUE THREAD

**Issue by define-private-public** [raysan5/raylib#335] opened 2017-07-25 01:05 UTC
The sphere collision doesn't look right...

![bad-collision-1](https://user-images.githubusercontent.com/4551425/28551123-d701de72-70b3-11e7-9942-1d601b0c758f.png)

![bad-collision-2](https://user-images.githubusercontent.com/4551425/28551122-d701296e-70b3-11e7-8324-57c49ea91f13.png)

**Comment by raysan5** [comment] 2017-07-25 15:57
Are you using latest develop branch? In you screenshots ball seems out of place, that's what I see in my computer:
![screenshot000](https://user-images.githubusercontent.com/5766837/28581431-77c766ca-7162-11e7-8288-746547c9fca0.png)
Being doing lots of changes in internal maths system, please recompile latest develop branch.

**Comment by define-private-public** [comment] 2017-07-25 16:11
Yeah, that was from the `develop` branch.  When I get home I'll take another look at it.

**Comment by raysan5** [comment] 2017-07-25 16:17
Just tested it now... it should work...

**Comment by define-private-public** [comment] 2017-07-26 02:50
The sphere is still out of place for me.  I can test this on my OS X machine later any on my laptop tomorrow.  I'm not sure what's up.  I just rebased from `develop` a few minutes ago.

**Comment by raysan5** [comment] 2017-07-26 08:29
Reviewed again, it's ok for me. Please, could you verify this line: https://github.com/raysan5/raylib/blob/develop/src/models.c#L333

It must be `rlScalef()` and `rlTranslatef()` and not the other way round, it changed some days ago. Just clean installation and try to recompile again, maybe some old version of the library is installed around...

**Comment by define-private-public** [comment] 2017-07-26 23:36
I check on another one of my Linux boxes and it isn't working right.  Doing a diff between your `develop` branch and my `cmake_test` doesn't have any differences between any source (other than Makefiles).

I also tested this on OS X, same problem is happening.  The collisions are happening where they are supposed to be, but well, it's the drawing of the sphere that is out of place.

Can you make a second example that has around 5 shapes?  It would be a better test than two.  When I was writing a ray tracer a couple of months ago the first object seemed fine if it was transformed, but when I started adding more and more objects it started to get crazy misplaced.  Turns out it was an issue with un-poping a matrix.

**Comment by raysan5** [comment] 2017-07-27 06:53
ok, I found the problem. It seems you're compiling raylib with flag `GRAPHICS_API_OPENGL_11` to use OpenGL 1.1 backend instead of OpenGL 3.3.

Last week I reviewed raymath library and I messed something up, I mean I corrected lots of maths for OpenGL 3.3 but I reversed OpenGL 1.1 expected behaviour.

Just need to review `rlTranslate()`, `rlScale()` and `rlRotate()` implementations, probably just transposing the matrices before multiplication.

**Comment by define-private-public** [comment] 2017-07-27 13:01
Any reason why raylib supports such and out of date version of OpenGL?  I know it's nice to say that we're backward compatible, but that API terribly old.  I think it would be less likely to have hangups like this if OpenGL 1.1 support was dropped.

While it only lists DirectX at the moment, I think taking a look at the Valve Hardware Survey would be a good metric to see which version(s) of OpenGL are relevant: http://store.steampowered.com/hwsurvey/videocard/

**Comment by define-private-public** [comment] 2017-07-27 22:12
Yeah, this is an OpenGL 1.x issue.  I tried building using non 1.x and the sphere was in the correct location.

As for my previous comment of dropping OpenGL 1.x support, that might be something for a different discussion, or within another release or two of raylib.  I'll leave that up to you.  (my $0.02 though).

**Comment by raysan5** [comment] 2017-07-28 08:39
About OpenGL 1.1 support: https://github.com/raysan5/raylib/issues/334

I think OpenGL 1.1 immediate mode is quite useful to introduce students to graphics programming, that's the reason of [rlgl](https://github.com/raysan5/raylib/blob/develop/src/rlgl.c); actually that layer just emulates a fixed function pipeline over a programmable one, letting the user code in an immediate mode style but translating calls to internal buffers and shaders use.

**Comment by define-private-public** [comment] 2017-07-28 13:08
Yeah, I can understand that.  I've had my CG professors say that OpenGL 1.x is much easier to understand for new comers.  It's good that you're already trying to emulate it, but I think it would be best to actually drop it in the backend.

That way your users can have the OpenGL 1.x feel, but you won't have to actually maintain a legacy API.

**Comment by raysan5** [comment] 2017-08-04 16:37
Transforms corrected on commit https://github.com/raysan5/raylib/commit/eeca607506b22f154a7b31ef8308d3ecd30ad383

Now rlgl OpenGL 1.1 emulation matches OpenGL 1.1 expected behaviour.

Please, close the bug if it works on your side.

**Comment by raysan5** [comment] 2017-08-06 19:12
Just closing it, please feel free to reopen if issue persist.

**Closed by raysan5** 2017-08-06 19:12 UTC

**Comment by define-private-public** [comment] 2017-08-06 22:19
Yeah, it's all good.
