### ISSUE TITLE
PlaySound working but can't hear the sound

### ISSUE THREAD

**Issue by Patchap1** [raysan5/raylib#4376] opened 2024-10-10 16:47 UTC
Hello,

I was trying to add sound to my game using Raylib, but I can't hear anything. However, when I look at the console, it says that the sound and the music stream were loaded successfully (I even added code to show 0 if no sound is playing and 1 if a sound is playing). So I’m guessing I’m missing something to be able to hear it, or the sounds I’m using are incompatible. Can someone help me understand the problem, please?

![image_2024-10-10_184908841](https://github.com/user-attachments/assets/60dafb16-7c99-4a84-b9ad-dee24276f1e2)

![image](https://github.com/user-attachments/assets/5f082c60-1d19-4e73-8a50-b9996e08000a)

![image](https://github.com/user-attachments/assets/3c2aea8e-2aa5-4805-9efd-585b2c76cc1e)

**Comment by raysan5** [comment] 2024-10-10 17:09
@Patchap1 Did you try the audio examples? Do they work? If they work then issue could be in your code.
As per the shared code, everything seems fine... except that list of values in the log that I imagine you `printf()`.

**Comment by Patchap1** [comment] 2024-10-10 17:27
What do you mean by audio examples? And regarding the list of values in the log, yes, it is from the printf() function, and you can clearly see a line of 1, which means the sound was played but couldn't be heard.

**Comment by raysan5** [comment] 2024-10-10 18:52
> What do you mean by audio examples? 

@Patchap1 I mean the [raylib audio examples](https://github.com/raysan5/raylib/tree/master/examples/audio) included with the library. If you are on Windows, you can open the provided VS2022 solution and try them.

**Comment by gen2brain** [comment] 2024-10-10 21:22
@Patchap1 You have `Backend: miniaudio / Null`, so with Null backend there is no sound. Try the examples first. What OS is that?

**Comment by gen2brain** [comment] 2024-10-10 21:47
You can check two similar issues but on macOS https://github.com/mackron/miniaudio/issues/750 and https://github.com/gen2brain/raylib-go/issues/274. It can also happen on distros with non-standard file system layout because miniaudio will dlopen/runtime link the libraries.

**Comment by raysan5** [comment] 2024-10-12 11:16
It seems the issue is out of scope of raylib and it can rely on OS configuration or miniaudio library.

**Closed by raysan5** 2024-10-12 11:16 UTC

**Comment by Patchap1** [comment] 2024-10-12 14:24
Sorry I'm kinda new so I don't know how to use the exemples. 
Can you explain please ?

**Comment by Patchap1** [comment] 2024-10-12 14:36
AH ! Nevermind I found the issue, it was because I wasn't including miniaudio.h...
