### ISSUE TITLE
[releases] No binaries in latest (4.2.0) mingw release 

### ISSUE THREAD

**Issue by hatkidchan** [raysan5/raylib#2697] opened 2022-09-15 20:53 UTC
Please, before submitting a new issue verify and check:

 - [-] I tested it on latest raylib version from master branch
 - [+] I checked there is no similar issue already reported
 - [+] My code has no errors or misuse of raylib

### Issue description

There are binaries of raylib in previous release (3.7.0), but not in latest one (4.2.0).
I'm talking about `lib/{raylib.dll,libraylib.a,libraylibdll.a}`

### Environment

win32 mingw

### Issue Screenshot

not applicable

### Code Example

not applicable

**Comment by JeffM2501** [comment] 2022-09-15 20:57
duplicate of #2698

**Closed** 2022-09-16 07:46 UTC
