### ISSUE TITLE
[rcore] `GetFrameTime()` counts time since application was minimized

### ISSUE THREAD

**Issue by Volcanic-Penguin** [raysan5/raylib#4588] opened 2024-12-09 14:57 UTC
### Issue description

I'm using Raylib 5.0 with Rust but I'm presuming this is not a Rust specific bug. If it is then I'm sorry for wasting your time. If you minimize a Raylib application, when you unminimize the app, GetFrameTime() will return the total amount of time that has passed since you minimized the app. I feel like this probably shouldn't happen, anything that's moving based on frame time will move way too far when opening a minimized application, so you could probably clip through walls and stuff. 

### Environment

Raylib 5.0 with Rust (raylib-rs)
Windows 10
Platform backend: DESKTOP (GLFW)
Renderer: Intel(R) HD Graphics 530

### Code Example

Just print GetFrameTime() to the console if it's more than one second, so something like: 

```
if GetFrameTime() > 1.0 {
  printf(GetFrameTime());
}
```

**Comment by asdqwe** [comment] 2024-12-09 21:32
Out of curiosity, I tried reproducing this issue directly with GLFW and the iconifying freeze didn't happen.

<details>
<summary>GLFW test case:</summary>
<br>

```
//     How to replicate:
// unzip glfw-master.zip
// cd glfw-master/
//     Pick any example from examples/ and replace its code with this source.
//     Then:
// mkdir build/
// cmake -S . -B build/
// cmake --build build/
// ./build/examples/example

#include <stdio.h>
#define GLAD_GL_IMPLEMENTATION
#include <glad/gl.h>
#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

int main(int argc, char** argv) {

    glfwInit();
    glfwWindowHint(GLFW_CONTEXT_VERSION_MAJOR, 2);
    glfwWindowHint(GLFW_CONTEXT_VERSION_MINOR, 0);

    GLFWwindow* window;
    window = glfwCreateWindow(640, 480, "test", NULL, NULL);
    if (!window) { glfwTerminate(); exit(EXIT_FAILURE); }

    glfwMakeContextCurrent(window);
    gladLoadGL(glfwGetProcAddress);
    glClearColor(1.0f, 1.0f, 1.0f, 1.0f);
    glfwSwapInterval(1);

    while (!glfwWindowShouldClose(window)) {
        printf("%f\n", glfwGetTime());

        glClear(GL_COLOR_BUFFER_BIT);
        glfwSwapBuffers(window);
        glfwPollEvents();
    }

    glfwDestroyWindow(window);
    glfwTerminate();
    exit(EXIT_SUCCESS);

}
```
</details>

Then I rolled back raylib as far as `3.0.0` (from 2020) and, to my surprise, the issue happened even there (although I had to add `MinimizeWindow()`/`glfwIconifyWindow()` that wasn't implemented back then, `HideWindow()` was a different thing).

<details>
<summary>raylib 3.0.0 test case:</summary>
<br>

```
INFO: Initializing raylib 3.0
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1600 x 900
INFO:     > Render size:  800 x 450
INFO:     > Screen size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: OpenGL 3.3 Core profile supported
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 3000 (SNB GT2)
INFO:     > Version:  3.3 (Core Profile) Mesa 24.0.9-0ubuntu0.2
INFO:     > GLSL:     3.30
INFO: GL: Supported extensions count: 174
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: GL: Anisotropic textures filtering supported (max: 16X)
INFO: TEXTURE: [ID 1] Texture created successfully (1x1 - 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Compiled successfully
INFO: SHADER: [ID 2] Compiled successfully
INFO: SHADER: [ID 3] Program loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Internal vertex buffers initialized successfully in RAM (CPU)
INFO: RLGL: Internal vertex buffers uploaded successfully to VRAM (GPU)
INFO: RLGL: Default state initialized successfully
INFO: TEXTURE: [ID 2] Texture created successfully (128x128 - 1 mipmaps)
INFO: FONT: Default font loaded successfully
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: GetTime():0.102898. GetFrameTime():0.000000.
INFO: GetTime():0.109237. GetFrameTime():0.016870.
INFO: GetTime():0.125903. GetFrameTime():0.016667.
INFO: GetTime():0.142571. GetFrameTime():0.016667.
INFO: GetTime():0.159238. GetFrameTime():0.016667.
INFO: GetTime():0.175905. GetFrameTime():0.016667.
INFO: GetTime():0.192572. GetFrameTime():0.016667.
INFO: GetTime():0.209239. GetFrameTime():0.016667.
INFO: GetTime():0.225906. GetFrameTime():0.016667.
INFO: GetTime():0.242574. GetFrameTime():0.016667.
INFO: GetTime():0.259241. GetFrameTime():0.016667.
INFO: GetTime():0.275907. GetFrameTime():0.016667.
INFO: GetTime():0.292575. GetFrameTime():0.016667.
INFO: GetTime():0.309243. GetFrameTime():0.016667.
INFO: Minimized
INFO: GetTime():0.326415. GetFrameTime():0.016667.
INFO: GetTime():0.342577. GetFrameTime():0.016667.
INFO: GetTime():2.574575. GetFrameTime():0.016668.
INFO: GetTime():2.575251. GetFrameTime():2.216007.
INFO: GetTime():2.591920. GetFrameTime():0.016668.
INFO: GetTime():2.608588. GetFrameTime():0.016668.
INFO: GetTime():2.625255. GetFrameTime():0.016667.
INFO: GetTime():2.641922. GetFrameTime():0.016667.
INFO: GetTime():2.658590. GetFrameTime():0.016667.
INFO: GetTime():2.675258. GetFrameTime():0.016667.
INFO: GetTime():2.691925. GetFrameTime():0.016667.
INFO: GetTime():2.708593. GetFrameTime():0.016667.
INFO: GetTime():2.725259. GetFrameTime():0.016667.
INFO: GetTime():2.741925. GetFrameTime():0.016667.
INFO: GetTime():2.758594. GetFrameTime():0.016667.
INFO: GetTime():2.775261. GetFrameTime():0.016667.
INFO: GetTime():2.791929. GetFrameTime():0.016667.
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: TEXTURE: [ID 1] Unloaded default texture data from VRAM (GPU)
INFO: Window closed successfully
```
</details>

And then I returned to the current master branch ([aeb33e6](https://github.com/raysan5/raylib/tree/aeb33e6301fd614e1f38aed66ab6b219a824df3c)) and tested again removing `SwapScreenBuffer()` from `rcore.c` ([ref](https://github.com/raysan5/raylib/blob/aeb33e6301fd614e1f38aed66ab6b219a824df3c/src/rcore.c#L937)), which obviously broke the render, but was still able to open the window, minimize it and the issue was still there. So I guess we can rule that out.

<details>
<summary>raylib current master branch without SwapScreenBuffer test case:</summary>
<br>

```
INFO: Initializing raylib 5.6-dev
INFO: Platform backend: DESKTOP (GLFW)
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1600 x 900
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 174
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Intel
INFO:     > Renderer: Mesa Intel(R) HD Graphics 3000 (SNB GT2)
INFO:     > Version:  3.3 (Core Profile) Mesa 24.0.9-0ubuntu0.2
INFO:     > GLSL:     3.30
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: PLATFORM: DESKTOP (GLFW - X11): Initialized successfully
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
INFO: SYSTEM: Working Directory: /home/username/raylib-master/examples/core
INFO: TIMER: Target time per frame: 16.667 milliseconds
INFO: GetTime():0.085478. GetFrameTime():0.000000.
INFO: GetTime():0.099596. GetFrameTime():0.016667.
INFO: GetTime():0.104716. GetFrameTime():0.016667.
INFO: GetTime():0.121345. GetFrameTime():0.016667.
INFO: GetTime():0.138001. GetFrameTime():0.016667.
INFO: GetTime():0.154666. GetFrameTime():0.016667.
INFO: GetTime():0.171354. GetFrameTime():0.016667.
INFO: GetTime():0.188024. GetFrameTime():0.016667.
INFO: GetTime():0.204701. GetFrameTime():0.016667.
INFO: GetTime():0.221376. GetFrameTime():0.016667.
INFO: GetTime():0.238046. GetFrameTime():0.016668.
INFO: GetTime():0.254720. GetFrameTime():0.016668.
INFO: GetTime():0.271389. GetFrameTime():0.016668.
INFO: Minimized
INFO: GetTime():0.288958. GetFrameTime():0.016668.
INFO: GetTime():2.193007. GetFrameTime():0.016668.
INFO: GetTime():2.193109. GetFrameTime():1.888420.
INFO: GetTime():2.221997. GetFrameTime():0.016668.
INFO: GetTime():2.226468. GetFrameTime():0.016668.
INFO: GetTime():2.243483. GetFrameTime():0.016668.
INFO: GetTime():2.259815. GetFrameTime():0.016667.
INFO: GetTime():2.276477. GetFrameTime():0.016668.
INFO: GetTime():2.293133. GetFrameTime():0.016668.
INFO: GetTime():2.309814. GetFrameTime():0.016668.
INFO: GetTime():2.326483. GetFrameTime():0.016668.
INFO: GetTime():2.343145. GetFrameTime():0.016668.
INFO: GetTime():2.359864. GetFrameTime():0.016668.
INFO: GetTime():2.376531. GetFrameTime():0.016668.
INFO: GetTime():2.393207. GetFrameTime():0.016668.
INFO: GetTime():2.409882. GetFrameTime():0.016668.
INFO: TEXTURE: [ID 2] Unloaded texture data from VRAM (GPU)
INFO: SHADER: [ID 3] Default shader unloaded successfully
INFO: TEXTURE: [ID 1] Default texture unloaded successfully
INFO: Window closed successfully
```
</details>

So, looks like the issue is indeed with raylib (`PLATFORM_DESKTOP_GLFW`).

**Comment by asdqwe** [comment] 2024-12-09 22:40
Ok, found the issue. Inside the `PollInputEvents()`, that is called in the end of `EndDrawing()` ([ref](https://github.com/raysan5/raylib/blob/aeb33e6301fd614e1f38aed66ab6b219a824df3c/src/rcore.c#L958)), there's this:
https://github.com/raysan5/raylib/blob/aeb33e6301fd614e1f38aed66ab6b219a824df3c/src/platforms/rcore_desktop_glfw.c#L1254-L1255
Which is stopping execution because `FLAG_WINDOW_ALWAYS_RUN` is false by default. So, a simple `SetWindowState(FLAG_WINDOW_ALWAYS_RUN);` call solves this issue.

<details>
<summary>Fix test case:</summary>
<br>

```
#include "raylib.h"
int main(void) {
    InitWindow(800, 450, "test");
    SetTargetFPS(60);

    SetWindowState(FLAG_WINDOW_ALWAYS_RUN); // This fixes it.

    while (!WindowShouldClose()) {

        if (IsKeyPressed(KEY_ONE)) { MinimizeWindow(); TraceLog(LOG_INFO, "Minimized"); }

        TraceLog(LOG_INFO, "GetTime():%f. GetFrameTime():%f.", GetTime(), GetFrameTime());

        BeginDrawing();
        ClearBackground(RAYWHITE);
        EndDrawing();
     }
    CloseWindow();
    return 0;
}
```
</details>

@raysan5 Maybe the `FLAG_WINDOW_ALWAYS_RUN` should be enabled by default, what do you think? Let me know if I should send a PR to add it to `InitPlatform()`.

**Comment by Volcanic-Penguin** [comment] 2024-12-10 12:08
Wow well done, thanks for the fix!

That being said, I think that ideally you should be able to set `FLAG_WINDOW_ALWAYS_RUN` to false and still have `GetFrameTime()` work properly when the application stops and starts. I don't know how `GetFrameTime()` actually works but I could imagine maybe storing the time when the application stops and starts and subtracting that from the frame time or something like that.

**Comment by asdqwe** [comment] 2024-12-10 13:06
The `FLAG_WINDOW_ALWAYS_RUN` appears to be implemented only for `PLATFORM_DESKTOP_GLFW` to leverage the `glfwWaitEvents()` to create a sort of "suspended state" (which I can totaly see the usefulness of, e.g.: tools). And `glfwWaitEvents()` will _"puts the calling thread to sleep until at least one event is available"_ ([doc](https://www.glfw.org/docs/3.3/group__window.html#ga554e37d781f0a997656c26b2c56c835e)), which is exactly what's happening. To workaround that it would be necessary to move the entire input polling to another thread, which, in my opinion, is completely unnecessary and would increase raylib code complexity considerably.

It's much easier to just default it to `true` (which would standardize the behavior with the other platforms) and keep the funcionality there for those that need it.

**Comment by asdqwe** [comment] 2024-12-26 18:25
@raysan5 Since #4598 was merged, this issue is now resolved. Forgot to retag it on the PR.

**Comment by raysan5** [comment] 2024-12-26 19:13
@asdqwe Sure! Thanks!

**Closed by raysan5** 2024-12-26 19:13 UTC
