### ISSUE TITLE
[raudio] Error when calling InitAudioDevice() for Web

### ISSUE THREAD

**Issue by Capital-Asterisk** [raysan5/raylib#2931] opened 2023-02-21 00:53 UTC
Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

Calling `InitAudioDevice()` for web builds causes a JS exception.

```
Uncaught TypeError: Module._malloc is not a function
```

This happens with all audio examples built with CMake on both Chromium and Firefox.

The call `Module._malloc` is from miniaudio.h.

A workaround is to replace the string `Module._malloc` with just `_malloc` in the JS file.

### Environment

Emscripten: 3.1.31-1
CMake: 3.25.2
OS: EndeavourOS (arch based)

### Issue Screenshot

![Screenshot_20230220_163146](https://user-images.githubusercontent.com/14708882/220220430-ed9f2f70-cd44-4365-8e37-3baf08dd5a42.png)

### Code Example

```bash
git clone https://github.com/raysan5/raylib.git
cd raylib
BUILD_EXAMPLES=1 emcmake cmake -DPLATFORM=Web -B build .
cmake --build build
```

**Comment by raysan5** [comment] 2023-02-21 13:02
@Capital-Asterisk Thanks for reporting, I verified this issue with latest emscripten 3.1.32 (upstream). Probably @mackron should be notified about it.

**Comment by mackron** [comment] 2023-02-22 08:33
Thanks. Is this new to Emscripten? That code has existed in miniaudio for ages and this is the first I've heard of this issue. Is `_malloc()` available with older versions of Emscripten as well?

**Comment by raysan5** [comment] 2023-02-22 08:50
@mackron I think this is new to Emscripten with latests releases. All the audio examples worked as expected last time I tried a couple of months ago. In any case, I will investigate a bit further and provide more info about it.

**Comment by mackron** [comment] 2023-02-22 09:01
I'm wondering if this might be the issue: https://github.com/emscripten-core/emscripten/issues/6368#issuecomment-375728851

But that doesn't explain how `_malloc()` (without the `Module` part) seems to magically make it work. Does it work if `-s "EXPORTED_FUNCTIONS=['_malloc']"` is added to emcc command line?

**Comment by raysan5** [comment] 2023-02-22 11:34
@mackron After further investigation and multiple tests (reverted to previous `raudio`/`miniaudio` versions), I can confirm this issue was actually introduced in `emscripten 3.1.31`, everything works as expected up to `emscripten 3.1.30`.

**Comment by raysan5** [comment] 2023-02-22 13:29
UPDATE: It seems it's a change in the library: https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3131---012623

Is it possible to avoid using `Module.` prefix in `miniaudio` _malloc call?

**Comment by mackron** [comment] 2023-02-22 21:56
I also just saw that release note and was about to mention the same thing. That'll be the problem. I don't know how to work around it without using `EXPORTED_FUNCTIONS`. That specific part of the code was actually a community contribution. I think I'll have to update the documentation in miniaudio to mention that you may need to add `_malloc` to the `EXPORTED_FUCTIONS` command line option.

**Comment by raysan5** [comment] 2023-02-24 12:40
@mackron Is it possible to just replace `Module._malloc` calls by `_malloc` calls? I think it will work but only for latest emscripten...

Adding `EXPORTED_FUNCTIONS` seems a quite cumbersome solution, actually it didn't worked for me, I got compilation errors (but probably my fault passing the flag).

**Comment by mackron** [comment] 2023-02-24 12:51
I'm not convinced yet that replacing `Module._malloc` with just `_malloc` is the correct solution. Is there documentation of some kind on `_malloc` and how it's different from `Module._malloc`? I haven't seen anything concrete in my searching so far. I don't want to just willy-nilly make that change without understanding it properly. From what I've seen, it sounds to me that `EXPORTED_FUNCTIONS` is the intended way to do it. I agree that it's not an ideal solution though. It would be good if there was an in-code way to make it so the function is always exported. I wonder if maybe I include a dummy function that's marked with `EMSCRIPTEN_KEEPALIVE` that just calls `malloc()` and `free()` - maybe that will cause Emscripten to export it without needing the command line option?

I'll be upgrading my version of Emscripten soon and testing this out for myself with the miniaudio examples.

**Comment by raysan5** [comment] 2023-02-24 14:31
@mackron As per the [Emscripten changelog](https://github.com/emscripten-core/emscripten/blob/main/ChangeLog.md#3131---012623) I understand `_malloc` is no longer an object of `Module` but I neither understand the implications of that change.

  > Symbols that were previously exported from native code, but only for internal reasons, are no longer exported on the Module object by default.

**Comment by mackron** [comment] 2023-02-24 22:21
I've upgraded my version of Emscripten and was able to reproduce the error. I've pushed a fix to the dev branch. Are you able to give the the dev branch a try before I do a release?

The change I made does not require the `EXPORTED_FUNCTIONS` thing. I realised that the current implementation is wrong anyway because it's bypassing the allocation callback system. The new version is a better implementation.

**Comment by raysan5** [comment] 2023-02-25 00:18
@mackron Thank you very much for the quick review and fix, tomorrow I will test it and let you know!

**Comment by mackron** [comment] 2023-02-25 02:14
I think I understand the whole `Module._malloc()` vs `_malloc()` thing now. I believe just `_malloc()` refers to the actual C `malloc()` function (or rather, Emscripten's emulation of `malloc()`), and `Modules._malloc()` is literally just a function pointer to `_malloc()`. I believe just using `_malloc()` as the original poster suggested would have been a solution. However, the better solution is what I've got in the dev branch because it properly makes use of miniaudio's allocation callbacks.

**Comment by raysan5** [comment] 2023-03-04 17:16
@mackron Excuse the late response. Tested latest `miniaudio` dev branch and it works as expected on latest `emscripten 3.1.32`.

**Closed by raysan5** 2023-03-04 17:16 UTC
Labels: html5
