### ISSUE TITLE
[example] models-skybox example does not work in HDR mode

### ISSUE THREAD

**Issue by JeffM2501** [raysan5/raylib#1792] opened 2021-05-26 17:51 UTC
The skybox example does not function if useHDR is set to true.
This seems to have been broken with commit

https://github.com/raysan5/raylib/tree/51f3129c5dfa4be70787fa9c4473335252abffcd

In this commit GenTextureCubemap was moved out of rlgl.h and a copy was put into models_skybox.c

Sadly I can not see what is different about the old version in rlgl.h and the new inline one. I'm not sure if it is how the code was transformed, or if there was some other change in the underlying rlgl code.

I did verify the example works with HDR in the commit before.

**Comment by raysan5** [comment] 2021-05-26 18:00
This issue seems a duplicate of https://github.com/raysan5/raylib/issues/1778

**Comment by raysan5** [comment] 2021-05-26 18:03
@JeffM2501 Thanks for detecting the commit where it broke! I think I can find the issue... :)

**Closed** 2021-05-26 18:22 UTC
