### ISSUE TITLE
[core] Redrawing render textures introduces artifacts with high DPI

### ISSUE THREAD

**Issue by Not-Nik** [raysan5/raylib#2924] opened 2023-02-14 22:34 UTC
### Issue description

Redrawing render textures to other render textures reduces quality and introduces artifacts. I saw these artifacts without the `FLAG_WINDOW_HIGHDPI`, but I could only create a minimal example with it.

### Environment

macOS 13.2.1 (22D68) on a MacBook Pro 2018, OpenGl 4.1

### Issue Screenshot

![screenrec001](https://user-images.githubusercontent.com/32980656/218878172-0607ff17-7456-4cef-8405-585de54aaf3d.gif)

### Code Example

```cpp
#include "raylib.h"

int main() {
    SetConfigFlags(FLAG_WINDOW_HIGHDPI);

    InitWindow(800, 450, "redraw render texture");

    RenderTexture rt = LoadRenderTexture(800, 450);

    BeginTextureMode(rt);
    ClearBackground(GRAY);

    DrawText("Test", 382, 217, 16, WHITE);

    EndTextureMode();
    SetTargetFPS(60);

    while (!WindowShouldClose()) {
        if (IsKeyDown(KEY_SPACE)) {
            RenderTexture ne = LoadRenderTexture(800, 450);

            BeginTextureMode(ne);
            DrawTextureRec(rt.texture,
                           Rectangle{0, 0, (float) rt.texture.width, (float) -rt.texture.height},
                           Vector2{0, 0},
                           WHITE);

            EndTextureMode();
            UnloadRenderTexture(rt);
            rt = ne;
        }

        BeginDrawing();
        ClearBackground(GRAY);

        DrawTextureRec(rt.texture,
                       Rectangle{0, 0, (float) rt.texture.width, (float) -rt.texture.height},
                       Vector2{0, 0},
                       WHITE);
        EndDrawing();
    }
    CloseWindow();

    return 0;
}
```

**Comment by raysan5** [comment] 2023-02-14 22:55
@Not-Nik This code structure is quite weird, never seen a use case like that but in any case, it seems a driver/GPU related issue, I'm not sure if it is a raylib related issue... it seems it could be the expected behaviour for the default blending mode?

**Comment by raysan5** [comment] 2023-02-14 23:00
Just tried a more common use case and it works as expected:
```c
int main()
{
    SetConfigFlags(FLAG_WINDOW_HIGHDPI);
    InitWindow(800, 450, "redraw render texture");

    RenderTexture rt = LoadRenderTexture(800, 450);
    RenderTexture ne = LoadRenderTexture(800, 450);
    
    BeginTextureMode(rt);
        ClearBackground(GRAY);
        DrawText("Test", 382, 217, 40, WHITE);
    EndTextureMode();
    
    SetTargetFPS(60);

    while (!WindowShouldClose())
    {
        if (IsKeyDown(KEY_SPACE))
        {
            BeginTextureMode(ne);
                ClearBackground(GRAY);
                DrawTextureRec(rt.texture, (Rectangle){0, 0, (float) rt.texture.width, (float) -rt.texture.height}, (Vector2){0, 0}, WHITE);
            EndTextureMode();
        }

        BeginDrawing();
            ClearBackground(GRAY);
            DrawTextureRec(ne.texture, (Rectangle){0, 0, (float) ne.texture.width, (float) -ne.texture.height}, (Vector2){0, 0}, WHITE);
        EndDrawing();
    }
    
    CloseWindow();

    return 0;
}
```

**Comment by Not-Nik** [comment] 2023-02-14 23:15
That is because this use case is only one "iteration" of mine, and the result of it gets discarded. There probably still are artifacts, just that they are so small that they aren't noticable.

About my use case:
I'm creating a GUI where minimizing draw calls is essential so anything already drawn should optimally not be drawn again. For example when rendering a text editor, removing a line is achieved by rendering the old rendered text up to that line and then after it, instead of drawing all the lines again. Then the old text is discarded and the new one used for display.

**Comment by raysan5** [comment] 2023-02-24 15:24
Afaik, this issue is outside raylib bounds, probably related to drawing with some blending/scaling caused by the high-dpi scaling. I can't see where raylib could cause it.

About the use case, you can use raylib `EnableEventWaiting()` function to avoid re-drawing screen if no input event occurs, I use it for most of my tools.

 > For example when rendering a text editor, removing a line is achieved by rendering the old rendered text up to that line and then after it, instead of drawing all the lines again. Then the old text is discarded and the new one used for display.

Afaik, it's way more efficient to just draw the full frame again than trying to draw just a piece of it.

I'm closing this issue as out-of-scope.

**Closed by raysan5** 2023-02-24 15:24 UTC
