### ISSUE TITLE
[rcore] Issue with texture with transparency when using open gl es2.0 (google angle) on macos

### ISSUE THREAD

**Issue by ypujante** [raysan5/raylib#3179] opened 2023-07-18 13:27 UTC
This is a follow up to my post on [discord](https://discord.com/channels/426912293134270465/706078465476001902/1130558894402445603)

The issue on macOS is that when using OpenGL ES 2.0 (implemented by Google Angle on macOS), then the texture is rendered with a "halo" where there is transparency:

<img width="96" alt="tape_opengl_es20" src="https://github.com/raysan5/raylib/assets/357116/624e6a48-b89c-4302-b7cc-97d947620325">

```text
INFO: GLAD: OpenGL ES2.0 loaded successfully
INFO: GL: Supported extensions count: 101
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Google Inc. (Apple)
INFO:     > Renderer: ANGLE (Apple, Apple M2 Max, OpenGL 4.1 Metal - 83.1)
INFO:     > Version:  OpenGL ES 3.0.0 (ANGLE 2.1.20982 git hash: f3e3810b917c)
INFO:     > GLSL:     OpenGL ES GLSL ES 3.00 (ANGLE 2.1.20982 git hash: f3e3810b917c)
```

When using the macOS (deprecated) built-in OpenGL there is no such issue:

<img width="85" alt="tape_opengl" src="https://github.com/raysan5/raylib/assets/357116/7c6a0fc4-035b-4055-9a7c-4bb4ef1d3c0f">

```text
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 43
INFO: GL: OpenGL device information:
INFO:     > Vendor:   Apple
INFO:     > Renderer: Apple M2 Max
INFO:     > Version:  4.1 Metal - 83.1
INFO:     > GLSL:     4.10
```

The code is very simple and does not do anything fancy:

```cpp
#define IMAGE_PNG_PATH "/absolute/path/to/image.png"

int main()
{
  InitWindow(800, 450, "raylib [core] example - basic window");

  auto tape = LoadTexture(IMAGE_PNG_PATH);
  //  SetTargetFPS(60);

  constexpr Color myGrayColor{153, 153, 153, 255};

  auto bgColor = myGrayColor;

  while (!WindowShouldClose())
  {
    if(IsKeyPressed(KEY_B))
      bgColor = BLACK;
    if(IsKeyPressed(KEY_R))
      bgColor = RED;
    if(IsKeyPressed(KEY_C))
      bgColor = myGrayColor;

    BeginDrawing();
    ClearBackground(bgColor);
    DrawTexture(tape, 10, 10, WHITE);
    EndDrawing();
  }

  UnloadTexture(tape);

  CloseWindow();

  return 0;
}
```

I am attaching a fully self-contained project which demonstrates the issue. It contains raylib 4.5 (but note that I did try with the latest version on master with the same outcome). There is a README with instructions on how to build and run:

Build
-----

It is a CMake project, so it builds very simply:

```cmake
> mkdir build
> cd build
> cmake ..
> cmake --build . --target raylib_issue
```

The option `USE_GOOGLE_ANGLE_MAC_OS` is `ON` by default which demonstrates the problem. If you set to `OFF` (make sure to delete the build dir and redo all the steps), it won't use OpenGL ES 2.0/Google Angle at which point there is no issue.

Run
---

* On macOS, you get a bundle. Run it by invoking `build/raylib_issue.app/Content/MacOS/raylib_issue` (to see the log in the output)

Note that I do not know if it is a raylib issue, a GLFW issue, a Google Angle issue or anything else. The Google Angle libraries are coming from Google Chrome (I did not build them), so I assume they should be working quite well...

[raylib-issue.zip](https://github.com/raysan5/raylib/files/12080825/raylib-issue.zip)

**Comment by ypujante** [comment] 2023-07-20 17:56
As I am investigating further the issue, I realized that you actually don't even need a texture. 

Using this simple code will show the issue:

```cpp
int main()
{
  InitWindow(800, 450, "raylib issue");

  constexpr Color ImGuiCol_FrameBg{40, 73, 122, 137};

  while (!WindowShouldClose())
  {
    BeginDrawing();
    ClearBackground(BLACK);
    DrawRectangle(10, 10, 100, 100, ImGuiCol_FrameBg);
    EndDrawing();
  }

  CloseWindow();

  return 0;
}
```

I am using the color that ImGui uses for their dark style frame background.

Using OpenGL ES 2.0 / Google Angle you get this:

<img width="518" alt="opengl_es2" src="https://github.com/raysan5/raylib/assets/357116/cc458f7a-4dca-4c3f-bd67-745ac336907f">

Using OpenGL / Native you get this (which is the "right" blue color for ImGui with a black background)

<img width="518" alt="opengl_native" src="https://github.com/raysan5/raylib/assets/357116/17135d83-e65d-4a40-828e-d37f6f065703">

**Comment by ypujante** [comment] 2023-07-21 13:23
@ubkp no it does not help

It looks like it is a RGB vs sRGB buffer issue vs blending issue, according to this [thread](https://discourse.glfw.org/t/issue-with-texture-with-transparency-when-using-open-gl-es2-0-google-angle-on-macos/2417/7)

I have no idea how to fix it yet

**Comment by raysan5** [comment] 2023-07-22 19:13
@ypujante Please, could you try using different alpha premultiply modes:
```c
BeginDrawing();
ClearBackground(BLACK);
BeginBlendMode(BLEND_MULTIPLIED);   // Try also with RL_BLEND_ALPHA_PREMULTIPLY
    DrawRectangle(10, 10, 100, 100, ImGuiCol_FrameBg);
EndBlendMode();
EndDrawing();
```

**Comment by raysan5** [comment] 2023-07-22 19:22
@ypujante Just finished reading the thread you shared and it seems the issue could be in the ANGLE implementation, did you try building it for web platform? It is supposed to also use ANGLE backend, despite the WebGL implementation, just to confirm the isssue is due to ANGLE.
Also, it should be tested in other platforms using OpenGL ES but with custom implementation (not GLFW), like Android or Raspberry Pi.

**Comment by ypujante** [comment] 2023-07-22 20:53
@raysan5 I did try with pretty much every blend mode possible and none of them fixed the problem

In my latest attempts (described in the thread you mention) I did have a (minor) breakthrough if I add the hint `glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_METAL);` prior to calling `InitWindow`: the blending/color issue is completely gone.

But now there is a frame rate issue which, even in unlocked mode, seems to be very low (but not below 60fps). Something seems very odd (if it was purely a performance issue why would it stick to 60fps...)

I am going to research this further as I just encountered this problem. 

But if that leads nowhere then I will go down one more layer into the Angle library. I have been trying to avoid this as much as possible since it requires installing build tools and others to compile (not a cmake based library...) and it is pretty daunting...

**Comment by raysan5** [comment] 2023-07-23 18:41
> In my latest attempts (described in the thread you mention) I did have a (minor) breakthrough if I add the hint `glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_METAL);` prior to calling InitWindow: the blending/color issue is completely gone.

Yeah, I read it, that's very strange... but actually, it's stranger the severe performance hit!

 > But if that leads nowhere then I will go down one more layer into the Angle library. I have been trying to avoid this as much as possible since it requires installing build tools and others to compile (not a cmake based library...) and it is pretty daunting...

Please, don't... it could be a real rabbit-hole of despair, I think it does not worth it...

**Comment by ypujante** [comment] 2023-07-24 17:32
@raysan5 I did go down the rabbit hole :) Compiling the library is actually not that bad. It is the debugging/stepping in the code that is a challenge... until I figured out how to do it with CLion...

That being said, after many hours of more investigating, I have compiled my findings which I have posted on the [Angle forum](https://groups.google.com/g/angleproject/c/jpwKLJQAbs8).

I don't have a solution yet, but still investigating. If you feel like you want to close this issue, it's ok. I will still post what I come with either way. At this stage I am pretty convinced that it is not a raylib issue.

Finding the glfw hint really was the significant breakthrough that forced using metal and was clearly completely misunderstood by the article I had read on how to use Angle on macOS (the internet....), since they were using the non metal implementation in the end (which is really fast but renders wrong with alpha).

**Comment by raysan5** [comment] 2023-07-24 17:51
@ypujante Wow! Thanks for reporting! I'll keep this issue open for a while, I'm curious about the cause of this issue.

Also, did you try this example with a Rapsberry Pi for `PLATFORM_DRM`? It uses OpenGL ES 2.0 and afaik, the Mesa provided implementation for it. Just to see if it has the same issue.

I would also recommend giving a try to `PLATFORM_WEB`, it uses the browser WebGL implementation, that internally translates to ANGLE.

**Comment by ypujante** [comment] 2023-07-24 17:55
No I did not get a chance to try with a different platform. How would I go about trying `PLATFORM_WEB`? Can you point me to an example that would use this?

**Comment by raysan5** [comment] 2023-07-24 18:00
Actually it's quite straight forward, raylib [examples Makefile](https://github.com/raysan5/raylib/blob/master/examples/Makefile.Web) comes preconfigured for it, but I can try it right now because I already have the environment setup (basically, emscripten installed).

In any case, here some detailed instructions: https://github.com/raysan5/raylib/wiki/Working-for-Web-(HTML5)

Results in some minutes...

**Comment by raysan5** [comment] 2023-07-24 18:09
Here the result!


Specs:

OS: Windows 10 Pro 64bit
Browser: Google Chrome Version 115.0.5790.102 (Official Build) (64-bit)

**Comment by raysan5** [comment] 2023-07-25 11:27
@ypujante Just updated the previous comment, for some reason yesterday I was not able to uplaod images...

It seems that WebGL backend results are the expected ones (afaik, internally it uses ANGLE, most probably mapped to Direct3D).

**Comment by ypujante** [comment] 2023-07-25 12:38
@raysan5 Thank you very much for running this test. And of course the result is exactly as expected with the proper color... 

I am getting more and more convinced that there is an issue with Angle when using the gl/clg renderer (ANGLE (Apple, Apple M2 Max, OpenGL 4.1 Metal - 83.1)).

I think I reached a conclusion for my project which I will share soon after I collect more data.

**Comment by ypujante** [comment] 2023-07-25 14:29
In order to get a feeling of what is really going on with the various limitations I ran a benchmark on my machine.

The benchmark code is the following:

```cpp
//  glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_METAL);

  std::random_device rd;  // a seed source for the random number engine
  std::mt19937 gen(rd()); // mersenne_twister_engine seeded with rd()

  std::uniform_int_distribution<> random_color(64, 255);
  std::uniform_int_distribution<> random_x(0, 700);
  std::uniform_int_distribution<> random_y(0, 350);

  constexpr int N = 100000;

  InitWindow(800, 450, "raylib issue");

  // SetTargetFPS(60);

  glfwSwapInterval(0);

  long frame = 0;
  auto begin = std::chrono::steady_clock::now();

  while(!WindowShouldClose())
  {
    frame++;
    BeginDrawing();
    ClearBackground(BLACK);
    for(int i = 0; i < N; i++)
      DrawRectangle(random_x(gen), random_y(gen), 100, 100, Color{(unsigned char) random_color(gen), (unsigned char) random_color(gen), (unsigned char) random_color(gen), 255});
    DrawFPS(190, 300);
    EndDrawing();
  }

  auto elapsed = std::chrono::duration_cast<std::chrono::seconds>(std::chrono::steady_clock::now() - begin).count();

  std::cout << frame << " frames in " << elapsed <<" seconds => " << static_cast<float>(frame) / static_cast<float>(elapsed) << " fps\n";

  CloseWindow();

  return 0;
```

The 3 "platforms" for the benchmark are

1. **Angle / Metal** which corresponds to the renderer: `ANGLE (Apple, ANGLE Metal Renderer: Apple M2 Max, Version 13.4 (Build 22F2073))` and is achieved by compiling with option `OPENGL_VERSION "ES 2.0"`, linking with Google Angle and uncommenting `glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_METAL)`
2. **Angle / OpenGL** which corresponds to the renderer: `ANGLE (Apple, Apple M2 Max, OpenGL 4.1 Metal - 83.1)` and is achieved by compiling with option `OPENGL_VERSION "ES 2.0"`, linking with Google Angle (no glfw hint!)
3. **Native OpenGL** which corresponds to the renderer: `Apple M2 Max` and is achieved by compiling/linking without Google Angle (uses deprecated native macOS OpenGL api)

## 100k Rectangles / no limit
This test displays enough triangles that we are well below the 60fps threshold.

| Platform       | CPU  | GPU | FPS  |
|----------------|------|-----|------|
| Angle / Metal  | 100% | 80% | 27.5 |
| Angle / OpenGL | 100% | 98% | 26.5 |
| Native OpenGL  | 90%  | 93% | 27.5 |

## 10k Rectangles / no limit

This test displays less triangles and as a result can achieve more than 60fps.

| Platform       | CPU  | GPU | FPS   |
|----------------|------|-----|-------|
| Angle / Metal  | 23%  | 45% | 62.5  |
| Angle / OpenGL | 100% | 98% | 258.4 |
| Native OpenGL  | 60%  | 96% | 174.2 |

## 10k Rectangles / 60fps cap

Same test as the previous one but with a 60fps cap.

| Platform       | CPU | GPU | FPS  |
|----------------|-----|-----|------|
| Angle / Metal  | 35% | 18% | 59.8 |
| Angle / OpenGL | 35% | 56% | 58.5 |
| Native OpenGL  | 33% | 38% | 59.2 |

## Observations

* Benchmark 2 clearly shows how Angle / Metal has this wait that clearly limits the framerate, because both CPU and GPU are way less than they could be
* Benchmark 1 then confirms that this active wait is actually not impacting the performances and achieve 100% CPU while not maxing out the GPU
* Benchmark 3 shows that when capped, Angle / Metal also performs really well with the GPU
* Overall Native OpenGL is actually performing quite good (although I am unclear why in benchmark 2, it shows that it is GPU limited before CPU...)

## Conclusion

This was run on my machine so take everything I say with a grain of salt as numbers may vary if run on a different machine of course. It seems that Angle / Metal overall is the winner. Yes there is a clear limitation when uncapped, but I am not entirely sure of the value of running uncapped, certainly not in my use case...
It is definitely a hassle to use it though as I found out for example that the libraries I embedded in the test zip file, end up triggering security warnings when I tried on a different machine (had to go into the macOS settings/privacy and security panel to authorize the library to be used... PITA...). I am sure if they were properly code signed that might be less of an issue...
Clearly using straight OpenGL is a good alternative. My real worry is that OpenGL is deprecated on macOS so one day or another Apple will yank support entirely at which point, using something like Angle might become a necessity...

**Comment by raysan5** [comment] 2023-08-04 16:44
@ubkp Re-testing again, that's what I got:

![image](https://github.com/raysan5/raylib/assets/5766837/9bb86252-c129-4ae6-9694-7a375a402de0)

**Comment by raysan5** [comment] 2023-08-05 07:59
@ubkp Sorry, I don't understand, `rlgl.h` is not requried to be in include directory, it's already linked into raylib. The library is only provided in case advance users want to use it independently of raylib. It's a single-file header-only OpenGL abstraction layer... but note that it's already linked into raylib by default, you can [see it here](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L121).

**Comment by raysan5** [comment] 2023-08-05 13:07
@ubkp Wow! That's a good catch! Sincerely, I can't remember when it was added or how it affected rendering!!! So... it seem it mixes with the framebuffer color.... interesting... 🤔

**Comment by ypujante** [comment] 2023-08-05 13:09
I think there is something there... clearly there is a way to reproduce it outside the macOS / Angle platform!

**Comment by raysan5** [comment] 2023-08-05 21:23
@ypujante could it be that ANGLE implementation is intended to work on web and already considers the `canvas` background for the blending but when running on desktop there is no `canvas` and the resulting framebuffer is not blended properly?

**Comment by ypujante** [comment] 2023-08-06 13:58
@raysan5 I do not know exactly, but the last answer on the Google Angle forum stated [this](https://groups.google.com/g/angleproject/c/jpwKLJQAbs8/m/nYqAGIJEAAAJ):

> 
> Window surfaces on MacOS are all emulated by ANGLE, they don't see a ton of usage because many of our integrators just use ANGLE to render into IOSurfaces and then composite themselves.
> 
> * It looks like frame pacing is [not implemented in our CGL backend](https://source.chromium.org/chromium/chromium/src/+/main:third_party/angle/src/libANGLE/renderer/gl/cgl/WindowSurfaceCGL.mm;l=315;drc=a4341e04fe2f3d789864b629f20ac0b656ad46e9). That's why you're seeing 17k fps.
> * I'm not sure how blending is determined when compositing.
>  * Apart from the erratic values you see, it sounds like displaySyncEnabled is doing what it's supposed to but not blocking in the eglSwapBuffers call because the first time the drawable is used in each frame is for the clear.
> 
> I'd recommend doing window management and compositing yourself on MacOS. Grab an IOSurface out of the window and make an EGLImage with it so ANGLE can render into it.
> 

At the end of the day, due to my earlier benchmark and @ubkp tests, depending on the platform, the recommended approaches are the following:

* for macOS, use OpenGL directly, or if using Angle, make sure to set the proper glfw hint: `glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_METAL);`
* for the web platform, make sure to set the background color properly `canvas.emscripten { border: 0px none; background-color: black; }`

**Comment by raysan5** [comment] 2023-08-06 18:49
@ypujante @ubkp sincerely, I think at this point the best solution is just leave it as it is. The problem has been tracked down and it seems to be beyond OpenGL, but on the underlaying composite system of the target platform, that's far beyond raylib domain.

The current solutions should work for any user:

 - for macOS, use OpenGL directly, or if using Angle, make sure to set the proper glfw hint: `glfwInitHint(GLFW_ANGLE_PLATFORM_TYPE, GLFW_ANGLE_PLATFORM_TYPE_METAL);`
 - for the web platform, make sure to set the background color properly `canvas.emscripten { border: 0px none; background-color: black; }`

Maybe document it in the Wiki (despite this issue is already a good documentation) for users facing this same problem.

@ubkp As per the Google Angle forum description, problem seems to be on EGL configuration. This issue should be tested on `PLATFORM_DRM` on Raspberry Pi, that uses OpenGL ES 2.0 native (no ANGLE layer) and configs the composite manually through EGL and KMS libs. If it works there (that I presume it will work as expected) then not much can be done on raylib side.

**Comment by ypujante** [comment] 2023-08-06 19:51
Yes I agree it's time to move on which is what I implied when I commented with the benchmark

**Comment by raysan5** [comment] 2023-08-06 20:00
@ypujante @ubkp thanks again for all your time and effort tracking this issue! Closing it! 😄

**Closed by raysan5** 2023-08-06 20:00 UTC
Labels: external
