### ISSUE TITLE
[core] `GetRenderWidth()`/`GetRenderHeight()` incorrect return values on retina display (HighDPI)

### ISSUE THREAD

**Issue by danielchasehooper** [raysan5/raylib#3367] opened 2023-10-02 20:11 UTC
### Issue description

On a retina display, these functions returned these values:
```c
GetWindowScaleDPI().x -> 2
GetScreenWidth() -> 1000
GetRenderWidth() -> 1000
```

### Environment

macOS, retina screen

### Code Example

```c
#include "raylib.h"

int main(void)
{
    InitWindow(1000, 450, "bug");

    while (!WindowShouldClose())
    {
        BeginDrawing();

        ClearBackground(RAYWHITE);

        EndDrawing();

        TraceLog(LOG_INFO, "GetWindowScaleDPI().x %g", GetWindowScaleDPI().x);
        TraceLog(LOG_INFO, "GetScreenWidth() %i", GetScreenWidth());
        TraceLog(LOG_INFO, "GetRenderWidth() %i", GetRenderWidth());
    }

    CloseWindow();  

    return 0;
}
```

**Comment by ubkp** [comment] 2023-10-02 20:13
@danielchasehooper I believe better HiDPI support is on the wishlist (#2952).

**Comment by raysan5** [comment] 2023-10-03 13:20
@danielchasehooper Just reviewed this issue, did you try calling `SetConfigFlags(FLAG_WINDOW_HIGHDPI)` before `InitWindow()`, it should do the trick, at least on `PLATFORM_DEKTOP`.

**Comment by danielchasehooper** [comment] 2023-10-03 15:07
mmm maybe I didn't explain the issue well enough. Here's better code to reproduce my issue
```c
#include <assert.h>
#include <stdarg.h>
#include "stdint.h"
#include "string.h"

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Weverything"

#include "raylib.h"
#include "raymath.h"
#include "rlgl.h"

#pragma clang diagnostic pop

int main(void){
    SetConfigFlags(FLAG_WINDOW_RESIZABLE);
    InitWindow(1000, 600, "framebuffer size bug");

    char *vshader =     
           "#version 330\n" 
    "in vec3 vertexPosition;            \n"
    "out vec4 fragColor;                \n"
    "uniform mat4 mvp;                  \n"
    "void main()                        \n"
    "{                                  \n"
    "    gl_Position = mvp*vec4(vertexPosition, 1.0); \n"
    "}                                  \n";

    char *fshader =  
    "#version 330\n \
    out vec4 finalColor; \
    uniform float framebuffer_width; \
    float random (vec2 st) {\
    return fract(sin(dot(st.xy,vec2(12.9898,78.233)))*43758.5453123);\
    }\
    void main() { \
    finalColor = vec4(vec3(gl_FragCoord.x/framebuffer_width, random(gl_FragCoord.xy/1000),0), 1); \
    } \
    ";

    Shader main_shader = LoadShaderFromMemory(vshader, fshader);
    int framebufferWidthLoc = GetShaderLocation(main_shader, "framebuffer_width");

    while (!WindowShouldClose()) {

        TraceLog(LOG_INFO, "GetScreenWidth() %i GetRenderWidth() %i GetWindowScaleDPI().x %g",GetScreenWidth(), GetRenderWidth(), GetWindowScaleDPI().x);
        float width =  (float)GetRenderWidth();
        SetShaderValue(main_shader, framebufferWidthLoc, &width, SHADER_UNIFORM_FLOAT);

        BeginDrawing(); {
            ClearBackground(RAYWHITE);
            BeginShaderMode(main_shader); 
            DrawRectangle(0, 0, GetScreenWidth(), GetScreenHeight(), WHITE);
            EndShaderMode();
        } EndDrawing();
    }

    return 0;
}

```

I expect the red channel to smoothly interpolate from 0 to 255 from the left to right edge of the window.
The green channel is noise to make it easier to see if the framebuffer is retina or not.

On a 1x screen we get what is expected. But on a 2x screen, the red gradient stops halfway along the buffer, because the buffer is actually retina even though GetRenderWidth is reporting a non-retina size

![Screenshot 2023-10-03 at 11 04 51 AM](https://github.com/raysan5/raylib/assets/1472250/654a2ed8-932e-4737-a23f-bc8686b29392)



So even though The code isn't calling `SetConfigFlags(FLAG_WINDOW_HIGHDPI)`, the framebuffer *is* 2x on a 2x screen, but `GetRenderWidth` is acting as if the framebuffer is 1x

**Comment by orcmid** [comment] 2023-10-03 16:25
> ### Issue description
> On a retina display, these functions returned these values:
> 
> ```c
> GetWindowScaleDPI().x -> 2
> GetScreenWidth() -> 1000
> GetRenderWidth() -> 1000
> ```

The `{2.0f, 2.0f}` return from `GetWindowScaleDPI()` suggests that you've got something like 200dpi instead of the 100dpi default assumption.  (On Windows it is 95dpi default, but we're in the same ball-park.)

That shouldn't have anything to do with `GetScreenWidth` though.  I think `InitWIndow` is in pixels, so technically you should scale those parameters.  The problem is that `GetWindowsScaleDPI()` reports on the display that the cursor is in (again, at least on Windows), and I think you have to do a trial `InitWindow` to get the scale at first, as someone already demonstrated here.  Then your graphical algorithm should work with that frame (in absolute, not scaled, pixels).  

[Fingers crossed that the whole arrangement is not buggy.]

**Comment by danielchasehooper** [comment] 2023-10-03 17:02
@orcmid I think you misunderstand what's going on. The window is the same size on both a 1x monitor and a 2x monitor. you can drag the window between monitors and its the same size *to your eye*, but the framebuffer that is backing the window doubles in width and height when you move it onto a retina screen. So the framebuffer size is double on a retina screen (as it should be), but `getrenderwidth` is not reporting that. The windows appear different sizes in the above screenshot because it's showing the backing framebuffer's pixels.

For what it's worth, "DPI" is not the right term for what `GetWindowScaleDPI()` is. Dots per inch is a product of the output device - a 27" 4k monitor and 30" 4k monitor have different dots per inch (same number of dots but different inches). But both monitors appear identical to software running on them. What we're discussing here is Pixels Per point – i.e. how many physical pixels make up each logical point on screen. So a 255 by 255 *point* window being displayed on a 2x retina screen is actually drawn to a 510 by 510 *pixel* framebuffer

**Comment by orcmid** [comment] 2023-10-03 17:28
@danielchasehooper 
> @orcmid I think you misunderstand what's going on. The window is the same size on both a 1x monitor and a 2x monitor. 

All I can say is that on my Windows PCs, The same `.exe` displays a window that is too small on my 200 dpi Windows laptop compared to on my 100 dpi (and now 110 dpi) desktop PC monitor that I used when I originally developed the raylib code that now shows up so differently.

I have not looked into GLFW to see what it does differently for a Mac.  I appreciate that the whole ppi thing can be murky with some displays, hardware, and operating systems.

**Comment by danielchasehooper** [comment] 2023-10-03 17:29
Ok, that may be a separate issue then. This is on macOS and presents differently.

**Comment by SoloByte** [comment] 2023-10-12 09:49
I have the same issue. (macOS Retina display) Setting `SetConfigFlags(FLAG_WINDOW_HIGHDPI)` has no effect and appears not to be set afterward.


### -Same window on 2 different monitors-

## 1920x1080 Monitor
![raylib-rendersize-1080pDisplay](https://github.com/raysan5/raylib/assets/34277803/67d1fedc-224f-43fb-9b01-527936d64d18)

## Retina Display
<img width="269" alt="raylib-rendersize-retinaDisplay" src="https://github.com/raysan5/raylib/assets/34277803/3b769045-8e2f-455c-8678-b02cabf2129e">

**Comment by raysan5** [comment] 2023-10-30 12:13
@danielchasehooper @SoloByte I've been looking into this issue, effectively it does not report the expected render size for the HighDPI but note this is platform-dependant issue, it only happens on macOS.

As per my understanding, macOS automatically increases the window and framebuffer size internally to accomodate to a HighDPI display, on other platforms the Window and framebuffer are the ones requested by user, consequently displaying smaller on a HighDPI display.

The issue is trickier than it seems because multiple functions depend on that an macOS-specific code should probably be implemented on all those situations (i.e. [`BeginScissorMode()`](https://github.com/raysan5/raylib/blob/master/src/rcore.c#L1068)).

Just pushed a quick fix for `GetRender*()` functions but there could be other functions presenting similar issues (not to mention other macOS versions inconsistencies).

**Comment by raysan5** [comment] 2023-10-30 12:26
As the HighDPI situation review is already on the future TODO list and this issue should be addressed with implemented fix, I'm just closing it.

**Closed by raysan5** 2023-10-30 12:26 UTC
Labels: platform: macOS
