### ISSUE TITLE
[raymath] Backwards parameter labels in `QuaternionFromVector3ToVector3 `

### ISSUE THREAD

**Issue by Sargates** [raysan5/raylib#3736] opened 2024-01-17 04:09 UTC
- [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [x] My code has no errors or misuse of raylib

### Environment
Desktop, Windows/WSL, OpenGL 330? (not exactly sure), RTX 4070 Ti

### Issue description / Code / Video demonstration

The parameter labels `from` and `to` are backwards for the `QuaternionFromVector3ToVector3` method.
This is what ***SHOULD*** (but doesn't) work:
```cpp
if (IsKeyPressed(KEY_P)) {
	if (!freeRotate) { // Free rotate is being disabled, reset the transforms up direction
		Game::player.transform.AddRotation(
			// Function sig per raymath.h: `Quaternion QuaternionFromVector3ToVector3(Vector3 from, Vector3 to)`
			//                             ~~~~~~~~~~~~ from ~~~~~~~~~~~~  ~~~~~ to ~~~~~
			QuaternionFromVector3ToVector3(Game::player.transform.GetUp(), Vector3{0,1,0})
		);
		Game::player.UpdateCamera();
	}
	freeRotate = !freeRotate;
}
```
- The game camera's `position`, `up`, and `target` properties are updated in the `player.UpdateCamera` method.
- `player.transform.GetUp` returns the relative normalized up vector of the transforms rotation (effectively the camera).
- The `player.transform.AddRotation` method just right multiplies the passed quaternion with the transforms rotation quaternion.

When I call `QuaternionFromVector3ToVector3` like the above it **should** return a quat that, when multiplied on `transform.rotation` using `transform.AddRotation`, should take the transforms `up` direction and rotate it to be inline with `{ 0, 1, 0}`, \
but it doesn't. What ends up working is using this instead:
```cpp
//                             ~~~~ from ~~~~  ~~~~~~~~~~~~~ to ~~~~~~~~~~~~~
QuaternionFromVector3ToVector3(Vector3{0,1,0}, Game::player.transform.GetUp());
```
Notice the arguments are just switched. This is backwards because what I should from this get is a quat that rotates  ***from*** `Vector3{0,1,0}` ***to*** `Game::player.transform.GetUp()`.
```cpp
// Intuitive. Doesn't work
//                             ~~~~~~~~~~~~ from ~~~~~~~~~~~~  ~~~~~ to ~~~~~
QuaternionFromVector3ToVector3(Game::player.transform.GetUp(), Vector3{0,1,0})

// Backwards. Has desired effect
//                             ~~~~ from ~~~~  ~~~~~~~~~~~~~ to ~~~~~~~~~~~~~
QuaternionFromVector3ToVector3(Vector3{0,1,0}, Game::player.transform.GetUp())
```

This is the demonstration. It contains code from the backwards code but working code.

https://github.com/raysan5/raylib/assets/78454343/405d584c-ab4c-46f3-b076-70d64b85323f

C/C++ is still a little new to me so maybe I'm messing something up and wrong about this, but I don't think so.
```cpp
// From: `raymath.h`
float cos2Theta = (from.x*to.x + from.y*to.y + from.z*to.z);    // Vector3DotProduct(from, to)
// Either each of the differences here need to be flipped
Vector3 cross = { from.y*to.z - from.z*to.y, from.z*to.x - from.x*to.z, from.x*to.y - from.y*to.x }; // Vector3CrossProduct(from, to)

// Or each of these need a negative sign in front, excluding the W component
result.x = cross.x;
result.y = cross.y;
result.z = cross.z;
result.w = 1.0f + cos2Theta;
```

The code for the `Transform` class I got from here: https://github.com/raylib-extras/examples-cpp/blob/main/transform_hierarchy/object_transform.h \
I got it from JeffM in the discord.
I modified it a little: renamed methods, added methods, but the functionality is still the same as the original.

**Comment by raysan5** [comment] 2024-01-31 23:13
@Sargates Thanks for reporting! Your reasoning seems correct to me but I'm not a math expert. Afair, that function was contributed by an user.

Feel free to send a PR with the review!

**Comment by Vlad-Zumer** [comment] 2024-02-09 17:45
@Sargates This isn't an issue with raylib. I suspect the problem is with `transform.AddRotation`, but i've not been able to find that method in the link you specified.

This code compiles and has the expected behaviour/output.

![image](https://github.com/raysan5/raylib/assets/21068598/f84e2b4e-16b6-4373-8c7c-0fbd90b04275)
![image](https://github.com/raysan5/raylib/assets/21068598/54947455-23c7-4d54-b364-7c9ef25aea97)

<details>
<summary> Full C code </summary>

```c
#include "raylib.h"
#include "rcamera.h"
#include "raymath.h"

//------------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------------
int main(void)
{
	// Initialization
	//--------------------------------------------------------------------------------------
	const int screenWidth = 800;
	const int screenHeight = 450;

	SetConfigFlags(FLAG_WINDOW_RESIZABLE);
	InitWindow(screenWidth, screenHeight, "Testing");

	// Define the camera to look into our 3d world
	Camera camera = { { 5.0f, 5.0f, 5.0f }, { 0.0f, 0.0f, 0.0f }, { 0.0f, 1.0f, 0.0f }, 45.0f, 0 };
	int updCamera = 1;


	// Model drawing position
	Vector3 Origin = { 0.0f, 0.0f, 0.0f };
	Vector3 XVec = { 5.0f, 0.0f, 0.0f };
	Vector3 YVec = { 0.0f, 5.0f, 0.0f };
	Vector3 ZVec = { 0.0f, 0.0f, 5.0f };

	Vector3 p1 = { 1.0f, 0.2f, 0.0f };
	p1 = Vector3Normalize(p1);
	Vector3 p2 = { 1.0f, 1.0f, 1.0f };
	p2 = Vector3Normalize(p2);

	Vector3 scale = { 0.3f,0.3f,0.3f };

	SetTargetFPS(60);               // Set our game to run at 60 frames-per-second
	//--------------------------------------------------------------------------------------

	// Main game loop
	while (!WindowShouldClose())    // Detect window close button or ESC key
	{
		// Update
		//----------------------------------------------------------------------------------
		if (updCamera)
		{
			UpdateCamera(&camera, CAMERA_ORBITAL);
		}
		//if (IsMouseButtonPressed(MOUSE_BUTTON_LEFT))
		//{
		//}

		if (IsKeyPressed(KEY_SPACE))
		{
			updCamera = 1 - updCamera;
		}

		// Draw
		//----------------------------------------------------------------------------------
		BeginDrawing();

		ClearBackground(RAYWHITE);

		BeginMode3D(camera);

		// DrawGrid(10, 1.0);
		DrawLine3D(Origin, XVec, RED);
		DrawLine3D(Origin, YVec, GREEN);
		DrawLine3D(Origin, ZVec, BLUE);

		DrawLine3D(Origin, p1, BLACK);
		DrawLine3D(Origin, p2, BLACK);
		// DrawCubeV(p1, scale, Fade(RED, 0.5));
		// DrawCubeV(p2, scale, Fade(GREEN, 0.5));

		Quaternion q = QuaternionFromVector3ToVector3(p1, p2);
		Vector3 vq = { q.x, q.y, q.z };
		DrawLine3D(Origin, vq, GOLD);

		Vector3 res = Vector3RotateByQuaternion(p1, q);
		DrawLine3D(Origin, res, PINK);

		EndMode3D();


		DrawRectangle(10, 10, 400, 100, Fade(LIGHTGRAY, 0.8));
		DrawRectangleLines(10, 10, 400, 100, Fade(LIGHTGRAY, 0.8));
		DrawText(TextFormat("P1: {%.3f, %.3f, %.3f}", p1.x, p1.y, p1.z), 15, 15, 20, BLACK);
		DrawText(TextFormat("P2: {%.3f, %.3f, %.3f}", p2.x, p2.y, p2.z), 15, 40, 20, BLACK);
		DrawText(TextFormat("Rotated: {%.3f, %.3f, %.3f}", res.x, res.y, res.z), 15, 60, 20, BLACK);
		DrawText(TextFormat("Quaternion: {%.3f, %.3f, %.3f, %.3f}", q.x, q.y, q.z, q.w), 15, 80, 20, BLACK);

		DrawRectangle(30, 400, 100, 30, Fade(DARKGRAY, 0.8f));
		DrawRectangleLines(30, 400, 100, 30, Fade(DARKBLUE, 0.8f));
		DrawFPS(35, 405);

		//DrawText("MOUSE LEFT BUTTON to CYCLE PROCEDURAL MODELS", 40, 410, 10, BLUE);


		EndDrawing();
		//----------------------------------------------------------------------------------
	}


	CloseWindow();          // Close window and OpenGL context
	//--------------------------------------------------------------------------------------

	return 0;
}
```

</details>

**Comment by Vlad-Zumer** [comment] 2024-02-09 17:53
@raysan5 There is however a quirk with the current implementation, that being that if you give `QuaternionFromVector3ToVector3` 2 vectors that are parallel to each other (e.g. `{1, 0, 0}` and `{-1, 0, 0}` ) the quaternion returned is 0, which makes sense because in that case there are infinitely many possibilities for the smallest rotation arc to align the 2 vectors. All those possibilities lie on the plane perpendicular to the 2 vectors.

To me it makes sense, but let me know if you want that behaviour changed.

**Comment by raysan5** [comment] 2024-02-10 17:22
> To me it makes sense, but let me know if you want that behaviour changed.

@Vlad-Zumer As per your explanation, it also make sense to me but I'm not a quaternions expert so I don't know if there is a better approach.

**Comment by Vlad-Zumer** [comment] 2024-02-10 19:25
To summarize my knowledge: 
A quaternion is basically an axis-angle representation. In maths literature you will see them defined as `q = a + bi + cj + dk` which translates into `(b, c, d, a)` for a `Vector4` of the form `(x, y, z, w)`. That is to say that:
- `i = X-axis ~ X comp of rotation axis`
- `j = Y-axis ~ Y comp of rotation axis`
- `k = Z-axis ~ Z comp of rotation axis`
- `1 ~ angle`

**_Only_** a unit quaternion can be thought of as a **_pure rotation_**.
Rotating `Vector3 v` by a `Quaternion q`, can be done with this equation: `v' = (p * v * p^(-1)).xyz`.
- **_Note_** that quaternion multiplication is **_not_** commutative.
- To multiply the quaternion we use the maths interpretation of `q = a + b*i + c*j + d*k`, and `v = 0 + v.x*i + v.y*j + v.z*k`, with keeping in mind the multiplication [table](https://en.wikipedia.org/wiki/Quaternion) for `i`,`j`,`k`.

Lastly the shortest arch of rotation between 2 `Vector3 u, v`  lies in the same plane described by those vectors, the plane is perpendicular to the cross product `u x v`.

So if `u` and `v` are parallel (for vectors we only care about direction) that means that they form one line, not a plane, and there are infinite planes that go through that line, or in other words the cross product `u x v = 0`. Which means that there are infinitely many planes for the shortest arch. (Note that this happens only in 2 cases, either the vectors have the same orientation already, or they have opposite directions.)

Hope this helped exmplain why there isn't really "a better approach", but is only up to what you want to do for computing rotations in those 2 cases. I think having '0' as "cannot compute **_unique_** shortest rotation between the 2 orientations" makes sense.

(Interactive demo for quaternion rotations: https://vlad-zumer.github.io/QuaternionVisualisation/)

**Comment by Vlad-Zumer** [comment] 2024-02-14 09:46
@raysan5 I think you can close this.

**Comment by raysan5** [comment] 2024-02-14 15:55
@Vlad-Zumer I think so! Thank you very much for the review and the detailed explanation!

**Closed by raysan5** 2024-02-14 15:55 UTC
