### ISSUE TITLE
[audio] Unable to play music audio.. but can play sound audio

### ISSUE THREAD

**Issue by cheesetaco123** [raysan5/raylib#957] opened 2019-09-01 17:02 UTC
I'm using code from GitHub as of 2019-09-01 for raudio.c/raudio.h  and running this stand-alone.  I'm into problems using the Music set of functions.  When I write the following:

`

	Music	music;

	InitAudioDevice();
	music = LoadMusicStream(argv[1]);
	PlayMusicStream(music);
	getchar();
	UnloadMusicStream(music);
	CloseAudioDevice();
`

It acts as if it's playing but actually, I get no audio output, and it shows when calling the function GetMusicTimePlayed(), it will stay at a consistent 0.

INFO: Audio device initialized successfully
INFO: Audio backend: miniaudio / WASAPI
INFO: Audio format: 32-bit IEEE Floating Point -> 32-bit IEEE Floating Point
INFO: Audio channels: 2 -> 2
INFO: Audio sample rate: 44100 -> 48000
INFO: Audio buffer size: 1440
INFO: Audio multichannel pool size: 16
INFO: Audio stream loaded successfully (44100 Hz, 32 bit, Stereo)
INFO: [C:\test\ff.mp3] MP3 sample rate: 44100
INFO: [C:\test\ff.mp3] MP3 bits per sample: 32
INFO: [C:\test\ff.mp3] MP3 channels: 2
INFO: [C:\test\ff.mp3] MP3 total samples: 9582336

Everything looks normal except that no audio is being played.

Now if I were to use the Sound set of functions everything works fine:

`
	Sound	sound;

	InitAudioDevice();
	sound = LoadSound(argv[1]);
	PlaySoundMulti(sound);
	getchar();
	UnloadSound(sound);
	CloseAudioDevice();
`

I'm compiling on Windows with Visual Studio 2013 x64.  Let me know if there's something that I'm missing?

**Comment by cheesetaco123** [comment] 2019-09-01 23:49
I tried a few things to see if I could debug the issue.  The first thing I tried was disabling various backends to see if that would make a difference using DirectSound and WinMM from the miniaudio.h to see if that would make a difference.  However, the results remained the same where audio only worked using the Sound related functions but nothing using Music.

I tried a different computer to see if maybe if it had something to do with my sound card, but also got the same result.

**Comment by raysan5** [comment] 2019-09-02 07:47
@cheesetaco123 did you try with different files and different file formats (.ogg, .mp3)?

**Comment by cheesetaco123** [comment] 2019-09-02 11:36
@raysan5, thank you for your reply.  I have tried the samples within the resources folder being chiptun1.mod, guitar_noodling.ogg, mini1111.xm, and tanatana.flac & .ogg versions using the Music functions.  It seems that using the Music API functions that I'm able to read all of these files.. but sadly no audio.

However using the Sound functions, I can hear the guitar_noodling.ogg, and tanatana.ogg.

Today, I'm going to try and install Visual Studio 2017 to see if maybe it's something to do with the version of compiler that I'm using and will report back.

**Comment by cheesetaco123** [comment] 2019-09-02 12:14
Sadly, I got the same results on Visual Studio 2017 as well on a totally different computer..  The last thing that I can think of is that I am building this stand-alone.  So to do this, maybe I should explain I am pulling the following files into a project:

dr_flac.h
dr_mp3.h
dr_wav.h
jar_mod.h
jar_xm.h
miniaudio.h
raudio.h
raudio.c
stb_vorbis.h
main.c

Then within the raudio.c, I had made the following modifications so that it would pull in the file format support, and allow it to run in this way.

```
#define RAUDIO_STANDALONE
#if defined(RAUDIO_STANDALONE)
#include "raudio.h"
#include <stdarg.h>         // Required for: va_list, va_start(), vfprintf(), va_end()
#else
#include "raylib.h"         // Declares module functions

// Check if config flags have been externally provided on compilation line
#if !defined(EXTERNAL_CONFIG_FLAGS)
#include "config.h"         // Defines module configuration flags
#endif
#include "utils.h"          // Required for: fopen() Android mapping
#endif
#define MA_NO_JACK
#define MINIAUDIO_IMPLEMENTATION
#include "miniaudio.h" // miniaudio library
#undef PlaySound                // Win32 API: windows.h > mmsystem.h defines PlaySound macro

#include <stdlib.h>             // Required for: malloc(), free()
#include <string.h>             // Required for: strcmp(), strncmp()
#include <stdio.h>              // Required for: FILE, fopen(), fclose(), fread()

#define SUPPORT_FILEFORMAT_OGG
#if defined(SUPPORT_FILEFORMAT_OGG)
#define STB_VORBIS_IMPLEMENTATION
#include "stb_vorbis.h"    // OGG loading functions
#endif

#define SUPPORT_FILEFORMAT_XM
#if defined(SUPPORT_FILEFORMAT_XM)
#define JAR_XM_IMPLEMENTATION
#include "jar_xm.h"        // XM loading functions
#endif

#define SUPPORT_FILEFORMAT_MOD
#if defined(SUPPORT_FILEFORMAT_MOD)
#define JAR_MOD_IMPLEMENTATION
#include "jar_mod.h"       // MOD loading functions
#endif

#define SUPPORT_FILEFORMAT_FLAC
#if defined(SUPPORT_FILEFORMAT_FLAC)
#define DR_FLAC_IMPLEMENTATION
#define DR_FLAC_NO_WIN32_IO
#include "dr_flac.h"       // FLAC loading functions
#endif

#define SUPPORT_FILEFORMAT_MP3
#if defined(SUPPORT_FILEFORMAT_MP3)
#define DR_MP3_IMPLEMENTATION
#include "dr_mp3.h"        // MP3 loading functions
#endif
```

Not sure if there's anything you could suggest anything else I could experiment with?

**Comment by cheesetaco123** [comment] 2019-09-02 12:31
should also add.. here's main.c  

```
#include <stdio.h>
#include "raudio.h"

int
main(int argc, char *argv[])
{

	Music	m;

	InitAudioDevice();
	m = LoadMusicStream(argv[1]);
	PlayMusicStream(m);
	getchar();
	UnloadMusicStream(m);
	CloseAudioDevice();
}
```

**Comment by raysan5** [comment] 2019-09-05 08:21
@cheesetaco123 Audio system was reviewed yesterday, please, could you try with latest version from github?

**Comment by cheesetaco123** [comment] 2019-09-06 23:02
@raysan5 Thank you for the attempts to look into the issue.  I have pulled the latest and tried the code, but sadly getting the same results.

**Comment by cheesetaco123** [comment] 2019-09-08 22:51
Let me know if there's any additional tests that I can try?

**Comment by raysan5** [comment] 2019-09-10 10:50
This is weird, I've done some tests and everything works perfect for me. Also, `Sound` playing uses exactly the same internal playing backend than `Music`, only difference is that `Music` is sent to device in pieces and `Sound` in one go... sorry, no idea what could happen, it should be debugged on your device...

**Comment by raysan5** [comment] 2019-09-13 11:04
Closing this issue for now.

**Closed by raysan5** 2019-09-13 11:04 UTC

**Comment by autopawn** [comment] 2021-03-21 19:47
I would like to report the same issue. I had an .ogg file and, although it was loaded correctly, it didn't play.

After some toying around I found that `GetMusicTimePlayed(·)` always returned 0, even though `IsMusicPlaying(·)` returned 1.

Finally, I could hear the music calling
```
UpdateMusicStream(music)
``` 
**on each frame**.

I am not sure is this workaround is efficient with the resources though.

**Comment by raysan5** [comment] 2021-03-21 19:55
@autopawn Actually, that's the expected behaviour. You must update the Music stream buffer every frame.

**Comment by autopawn** [comment] 2021-03-21 20:03
Sorry, I saw https://github.com/raysan5/raylib/issues/957#issuecomment-527130878 and I thought that it was right since nobody commented on it.

Maybe improving the comment
```
// Updates buffers for music streaming
```
on the cheatsheet, by adding something like `(this should be called on every frame)` could be useful. 

Although, my failure not looking at the examples.
