### ISSUE TITLE
[core] First keyboard input when running causes drawing to pause for very brief time. 

### ISSUE THREAD

**Issue by ismyhc** [raysan5/raylib#469] opened 2018-02-15 22:23 UTC
Latest raylib from brew.

Im not doing anything intensive at all. I have 100 structs that are drawn using DrawRectangleV() and do nothing more than move from top to bottom and reset back to top once at the bottom.  When pressing any key on the keyboard for the first time, it causes the small moving rectangles to pause for a brief time. Maybe 10ms? Doesn't happen anymore after the first key press until re-launching the game.

I can try and record a video if needed. Im running the latest macos.

Heres my very simple c file.

```c
#include <raylib.h>

//------------------------------------------------------------------------------
// Defines
//------------------------------------------------------------------------------

#define A_COUNT(x)  (sizeof(x) / sizeof((x)[0]))

#define SCREEN_WIDTH                    960
#define SCREEN_HEIGHT                   640

#define MAX_STARS                       100
#define MAX_STAR_SIZE                   8
#define MIN_STAR_SIZE                   4

//------------------------------------------------------------------------------
// Types and Structures Definition
//------------------------------------------------------------------------------

typedef struct str_star {
    
    Vector2 position;
    Vector2 size;
    float speed;
    Color color;
    
} str_star;

//------------------------------------------------------------------------------
// Program main entry point
//------------------------------------------------------------------------------

int main()
{
    
    // Initialization
    //--------------------------------------------------------------------------
    
    SetConfigFlags(FLAG_VSYNC_HINT);
    
    InitWindow(SCREEN_WIDTH, SCREEN_HEIGHT, "Test Raylib");
    
    SetTargetFPS(60);
    
    str_star stars[MAX_STARS];
    
    // Init Stars
    for (int i = 0; i < MAX_STARS; i++)
    {
        
        float x = GetRandomValue(0, SCREEN_WIDTH);
        float y = GetRandomValue(0, SCREEN_HEIGHT);
        float size = GetRandomValue(MIN_STAR_SIZE, MAX_STAR_SIZE);
        int r  = GetRandomValue(0, 255);
        int g  = GetRandomValue(0, 255);
        int b  = GetRandomValue(0, 255);
        
        stars[i].position = (Vector2) { x, y };
        stars[i].size = (Vector2) { size, size };
        stars[i].color = (Color) { r, g, b, 255 };
        stars[i].speed = size;
        
    }
    
    // Main game loop
    //--------------------------------------------------------------------------
    
    while (!WindowShouldClose())    // Detect window close button or ESC key
    {
        
//        if (IsKeyDown(KEY_SPACE))
//        {
//            // First time I press space, the moving stars stop for a breif period.
//            // doesnt happen again after the first key input.
//        }
        
        
        // Update
        //----------------------------------------------------------------------
        
        for (int i = 0; i < MAX_STARS; i++)
        {
            
            stars[i].position.y += stars[i].speed;
            
            if (stars[i].position.y > SCREEN_HEIGHT)
            {
                
                float x = (float)GetRandomValue(0, SCREEN_WIDTH);
                stars[i].position = (Vector2) { x, 0 };
                
            }
            
        }
        
        //----------------------------------------------------------------------
        
        // Draw
        //----------------------------------------------------------------------
        
        BeginDrawing();
        
        ClearBackground(BLACK);
        
        DrawFPS(10, 10);
        
        for (int i = 0; i < MAX_STARS; i++)
            DrawRectangleV(stars[i].position, stars[i].size, stars[i].color);
        
        EndDrawing();
        
        //----------------------------------------------------------------------
    }
    
    // De-Initialization
    //--------------------------------------------------------------------------
    
    CloseWindow();
    
    return 0;
    
}

```

**Comment by raysan5** [comment] 2018-02-16 11:19
Hi @ismyhc!

Sorry, just testing it but not experiencing this issue. I'm on Windows 10 64bit, Intel HD Graphics, mingw32 (gcc 7.2.0). What  is your system config?

It could be related to GLFW3, it's the library used to manage inputs on Desktop platforms but it's quite weird...

**Comment by ismyhc** [comment] 2018-02-16 13:46
@raysan5 yeah its really odd. Almost as if its lazily initialized or something... After the first input everything is as smooth as butter. Not a huge problem, but probably something that should be looked at. Im fairly new to C programing so I may not be much help, but ill try and do some searching around.

By the way my computer specs are:

macOS High Sierra 10.13.3
MacBook Pro (Retina, 13-inch, Late 2013)
2.4 GHz Intel Core i5
8 GB 1600 MHz DDR3
Intel Iris 1536 MB

I love raylib by the way. Such a great api.

-Jacob

**Comment by raysan5** [comment] 2018-02-19 11:05
Hi Jacob, did you notice that delay only with keyboard press? does it also happen with mouse button press or gamepad? could you try with a different keyboard (just in case)?

**Comment by ismyhc** [comment] 2018-02-20 15:02
@raysan5 I've just tried again this morning. Laptop keyboard and external keyboard would cause it to happen, but then it stopped. It tried again after a few min or so and it came back. I've been slow closing other applications to see if another application was causing it, but I have not pin pointed anything. I did just update macos to the latest this morning. Honestly I don't think its a big deal. Its probably some process that just happens to have a hold on the input until the raylib window grabs it. Im not really concerned about it. You could probably close this for now. :)

**Comment by raysan5** [comment] 2018-02-20 21:25
Hey @ismyhc, that's really weird... I liked to track that kind of crazy issues but unfortunately I don't have enough time at this moment.

I'm closing the issue, feel free to reopen it if you consider it necessary.

**Closed by raysan5** 2018-02-20 21:25 UTC

**Comment by jeanlauliac** [comment] 2024-01-04 22:47
I'm getting the same problem. The first time a key is pressed, getting a lag and as a result the press seems to be also missed in some occurrences (IsKeyPressed returns false and the press is never recorded). However to add to the weirdness of it all, the problem occurs separately with Arrow keys.

For example if I press "D" the first time, it gets skipped/lags, then the next times are fine. But if later on I press Down Arrow, the same problem occurs again, doesn't get recorded. The second and subsequent times I press Down Arrow, then it works fine. I'm thinking of implementing something based on IsKeyDown manually but haven't tried yet.

GetKeyPressed has the same issue.

I'm on MacOS 12 Intel chipset.

**Comment by jeanlauliac** [comment] 2024-01-05 23:13
> If I just run the compiled app without the debugger connected, it's fine.

Oh that's fascinating, I can confirm that. When I run the executable directly from the command line, no issues, it's smooth.  So not as much of an issue. Still odd, and quite possibly due to an underlying library rather than raylib.

**Comment by raysan5** [comment] 2024-01-05 23:51
This is a really strange issue, it seems it's a macOS platform issue... sincerely, no idea how to address it...

**Comment by JanDeVisser** [comment] 2024-03-21 01:56
I am/was having the same issue, also on MacOS: Run program, press key which should be 'caught' by `IsKeyPressed`, program hangs for approx. a second and `IsKeyPressed` does not return true. Press same key again and it works.

This was with the `brew` diistribution, which uses `PLATFORM=DESKTOP` I would assume. Compiling latest from git with `PLATFORM=SDL` results in a working program.

I haven't been able to do in-depth testing to see if there are any problems with using SDL, but unless those appear I will keep using the SDL version.

**Comment by JanDeVisser** [comment] 2024-03-21 03:05
> I am/was having the same issue, also on MacOS: Run program, press key which should be 'caught' by `IsKeyPressed`, program hangs for approx. a second and `IsKeyPressed` does not return true. Press same key again and it works.
> 
> This was with the `brew` diistribution, which uses `PLATFORM=DESKTOP` I would assume. Compiling latest from git with `PLATFORM=SDL` results in a working program.
> 
> I haven't been able to do in-depth testing to see if there are any problems with using SDL, but unless those appear I will keep using the SDL version.

Well that is weird. I tried it again and now there were a bunch of bugs in my app that only surfaced with SDL that I had to fix first and after doing that it still didn't work right. So I don't know what I was looking at earlier this evening. Back to the drawing board...

**Comment by steveruizok** [comment] 2024-07-19 17:49
I _think_ this is the same issue I'm seeing here.

![Kapture 2024-07-19 at 18 45 35](https://github.com/user-attachments/assets/953f396c-f053-490b-adea-5f0a03b53dce)

This is using the game template repo, and the inputs are based on mouse down / mouse ups. On mouse down there seems to be a long pause.

```c
// Gameplay Screen Update logic
void UpdateGameplayScreen(void)
{
    // snip, unrelated exit code

    if (IsMouseButtonDown(MOUSE_LEFT_BUTTON))
    {
        if (!app->isDrawing) {
                app->isDrawing = true;
                Line_init(&app->currentLine);
        }
        // add the current point to the line
        Line_addPoint(&app->currentLine, GetMousePosition());
        }
    }
    else
    {
        if (app->isDrawing)
        {
            // snip, If we're already drawing, finish the line and add it to the finished lines collection
        }
    }
}
```

**Comment by steveruizok** [comment] 2024-07-19 18:01
Did a bit more sleuthing—the engine doesn't hang but the mouse seems to freeze position on the window. This is with continuous user movement, but you can see the cursor appear to stop moving immediately after the mouse down.

https://github.com/user-attachments/assets/4d6ccc61-7936-4b79-b332-90d9d102ff0f

**Comment by webskydavid** [comment] 2024-10-08 11:41
Hi, have the same issue but only if I use CMake in VSCode to run the app in debug mode.
```cmake --build ./build --config Debug --target all --```

I have no lags if I run it directly from terminal.
My system is a MacBook Pro M1 10 core and Sonoma 14.4.1
