### ISSUE TITLE
[shapes] Small circles have gaps in them

### ISSUE THREAD

**Issue by BlueStaggo** [raysan5/raylib#2286] opened 2022-01-14 19:49 UTC
**WARNING: Please, read this note carefully before submitting a new issue:**

It is important to realise that **this is NOT A SUPPORT FORUM**, this is for reproducible BUGS with raylib ONLY.

There are lots of generous and helpful people ready to help you out on [raylib Discord forum](https://discord.gg/raylib) or [raylib reddit](https://www.reddit.com/r/raylib/).

Remember that asking for support questions here actively takes developer time away from improving raylib.

---

Please, before submitting a new issue verify and check:

 - [x] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

When I use the DrawCircle function with a small radius (I used 5), the circle draws with gaps in it.

### Environment

Platform: Windows 11 21H2
GPU: GeForce GTX 1650
OpenGL Version: 4.6

### Issue Screenshot

![image](https://user-images.githubusercontent.com/71090710/149576278-eac358e7-ed55-4602-aef6-1eb11da4ba11.png)

### Code Example

```c
#include "raylib.h"

int main(void)
{
    InitWindow(200, 200, "circle with holes");
    SetTargetFPS(60);

    while (!WindowShouldClose())
    {
        BeginDrawing();
            ClearBackground(RAYWHITE);
            DrawCircle(100, 100, 5.0f, GRAY);
        EndDrawing();
    }

    CloseWindow();

    return 0;
}

```

**Comment by Peter0x44** [comment] 2022-01-15 01:45
Using DrawCircle for this is very inefficient, I would suggest drawing to a texture first, and then drawing that.

But I personally cannot reproduce, the circle looks just fine for me, which is really strange.
Perhaps it's a driver problem or something of the sort? I really don't have a better guess....

**Comment by raysan5** [comment] 2022-01-16 12:07
@BlueStaggo This is a very weird issue... are you compiling raylib with OpenGL 4.3 support? what version of OpenGL are you using for raylib? Could you try updating the GPU drivers? Personally I never had this issue with Intel GPUs and NVIDIA should work way better.

**Comment by jdeokkim** [comment] 2022-01-16 16:05
I used to have this issue, but it no longer persists after updating my NVIDIA graphics driver to the latest ([GeForce 
Game Ready Driver v511.23](https://www.nvidia.com/Download/driverResults.aspx/185108/en-us)) version. No gaps inside circles even with or without the `FLAG_MSAA_4X_HINT` config flag.

![Circles](https://user-images.githubusercontent.com/28700668/149667679-6c6d58c0-6f70-4090-8bfe-6b29a3220501.PNG)

## Environment

- Platform: Windows 10 Pro (21H2)
- GPU: NVIDIA GeForce GTX 970
- OpenGL Version: 3.3

**Comment by raysan5** [comment] 2022-01-16 16:45
@jdeokkim Thank you very much for your feedback! Indeed it seems an issue with the drivers. I'm closing the issue.

**Closed by raysan5** 2022-01-16 16:45 UTC

**Comment by shiMusa** [comment] 2022-03-25 14:59
I just updated to latest Nvidia driver (512.15) and I still get the same issue, but only with `MSAA` activated:
MSAA on: 
![image](https://user-images.githubusercontent.com/17574234/160145904-1b10ff65-28b3-4d95-886c-27486f22b23e.png)
MSAA off:
![image](https://user-images.githubusercontent.com/17574234/160145986-30e47fef-f806-441f-8366-01fb4aa9ab3b.png)

**Comment by shiMusa** [comment] 2022-03-25 15:16
It seems, drawing two circles on top of each other causes this issue and it requires MSAA.  @Peter0x44 reproduced it (not Nvidia).
