### ISSUE TITLE
[core] Handling of keyboard layouts

### ISSUE THREAD

**Issue by minirop** [raysan5/raylib#1077] opened 2020-01-17 22:52 UTC
Please, before submitting a new issue verify and check:

 - [X] I tested it on latest raylib version from master branch
 - [X] I checked there is no similar issue already reported
 - [X] My code has no errors or misuse of raylib

### Issue description

Raylib uses internally GLFW that does not handle keyboard layouts. It assumes all keyboards are US-QWERTY.

### Environment

Computer with AZERTY keyboard.

### Code Example

```cpp
if (IsPressed(KEY_A))
{
    // I need to press "Q" for this condition to be true
}
```

### Trail?

Finding a way to convert the keycodes before passing it to GLFW.

**Comment by Softizo** [comment] 2020-01-18 03:31
Usually the user is the one that changes the keybindings within the game. However, some games do support different keyboard layouts out-of-the-box which is really useful. You can map scancodes to keycodes for portability versus using something like `GetKeyboardLayout` or `GetKeyboardLayoutNameA` which only work on Windows. This is something I would be willing to work on if I had a keyboard that wasn't QWERTY.

**Comment by raysan5** [comment] 2020-03-06 11:47
Closing this issue. No plans to work on that.

**Closed by raysan5** 2020-03-06 11:47 UTC
Labels: enhancement

**Comment by tjammer** [comment] 2022-03-14 20:57
One other point to note regarding keyboard layouts:

While the desktop builds always assume QWERTY, the build for browser will use whatever layout is actually configured in the OS (on linux anyway, but I assume the same is true for other OSs). So I'm getting different behaviours on different build targets.

This mismatch is unpleasant at best, if not a bug.

**Comment by oblerion** [comment] 2023-09-25 14:38
Hello,
I use azerty keyboard, 
so i have work for adapt raylib's function for more keyboard layout.
It work with qwerty and azerty keyboard.

https://github.com/oblerion/Kbd_layout_raylib

**Comment by oblerion** [comment] 2023-09-25 15:00
> Usually the user is the one that changes the keybindings within the game. However, some games do support different keyboard layouts out-of-the-box which is really useful. You can map scancodes to keycodes for portability versus using something like `GetKeyboardLayout` or `GetKeyboardLayoutNameA` which only work on Windows. This is something I would be willing to work on if I had a keyboard that wasn't QWERTY.


It possible to get keyboard's type only with windows OS (winuser.h). 
I find nothing for linux and mac.

**Comment by orcmid** [comment] 2023-09-25 16:10
I think this is another situation that merits an adapter layer that provides keyboard layout and related language information, along with what's needed to know about the display and its size and resolution, per discussion #3342.

@Softizo @oblerion 
> > Usually the user is the one that changes the keybindings within the game.

In my experience of keybinding settings in AAA games, keys are named by their (presumed) keytops.  This seems to be at a different level than mapping (supported) keycodes to keytops and the related assumptions about physical arrangement (i.e., the point of WASD on a wide variety of keyboards).

For a moderately-frightening account of all that can be involved, see https://en.wikipedia.org/wiki/Keyboard_layout

Based on this, I suspect there are ways to find out what is going on using Unix/Linux and also Mac OS.  How that extends to iOS and Android is a mystery for others to solve.

@tjammer 
>  the build for browser will use whatever layout is actually configured in the OS

In browsers, if we're talking about HTML, there is specification of character codes, accepting UTF8 for its generality.  Sometimes the specification in the HTTP header is incorrect and it can be over-ridden in at least some browsers.  I suspect browsers use OS functions with regard to user-entered data; browser choice may matter.  I am unclear how there is much control over data from the platform into the browser though.  And with regard to other software operated in a browser (e.g., JavaScript), I am clueless.

**Comment by SuperUserNameMan** [comment] 2023-09-26 09:35
> It possible to get keyboard's type only with windows OS (winuser.h). I find nothing for linux and mac.

Maybe you could have a look at Godot's source code : 
- Linux : https://github.com/godotengine/godot/blob/7e67b496ff7e35f66b88adcbdd5b252d01739cbb/platform/linuxbsd/x11/display_server_x11.cpp#L2920
- Macos : https://github.com/godotengine/godot/blob/7e67b496ff7e35f66b88adcbdd5b252d01739cbb/platform/macos/display_server_macos.mm#L3699

**Comment by oblerion** [comment] 2023-09-26 13:23
> > It possible to get keyboard's type only with windows OS (winuser.h). I find nothing for linux and mac.
> 
> Maybe you could have a look at Godot's source code :
> 
>     * Linux : https://github.com/godotengine/godot/blob/7e67b496ff7e35f66b88adcbdd5b252d01739cbb/platform/linuxbsd/x11/display_server_x11.cpp#L2920
> 
>     * Macos : https://github.com/godotengine/godot/blob/7e67b496ff7e35f66b88adcbdd5b252d01739cbb/platform/macos/display_server_macos.mm#L3699

godot use X11 for linux, i find glfw use it to.
I go to glfw's source in raylib and i find it:

wl_platform.h (linux) line 170
```cpp
typedef xkb_layout_index_t (* PFN_xkb_state_key_get_layout)(struct xkb_state*,xkb_keycode_t);
```
x11_platform.h (linux) line 135
```cpp
typedef KeySym* (* PFN_XGetKeyboardMapping)(Display*,KeyCode,int,int*);
```
cocoa_platform.h (macos) line 113
```cpp
typedef TISInputSourceRef (*PFN_TISCopyCurrentKeyboardLayoutInputSource)(void);
```
but i don't know to use it outside of glfw.
