### ISSUE TITLE
[build] Build failure in Raspberry PI Zero W 

### ISSUE THREAD

**Issue by pekdemir** [raysan5/raylib#2180] opened 2021-12-01 20:42 UTC
### Issue description

I am trying to build raylib on my Raspberry Pi Zero W, I get build error on rcore.c as the following:
```
pi@raspberrypi:~/raylib-master $ make
Scanning dependencies of target raylib
[  0%] Building C object raylib/CMakeFiles/raylib.dir/rcore.c.o
In file included from /usr/include/X11/Xlib.h:44,
                 from /usr/include/EGL/eglplatform.h:128,
                 from /usr/include/EGL/egl.h:39,
                 from /home/pi/raylib-master/src/rcore.c:254:
/usr/include/X11/X.h:100:13: error: conflicting types for ‘Font’
  100 | typedef XID Font;
      |             ^~~~
In file included from /home/pi/raylib-master/src/rcore.c:115:
/home/pi/raylib-master/src/raylib.h:296:3: note: previous declaration of ‘Font’ was here
  296 | } Font;
      |   ^~~~
/home/pi/raylib-master/src/rcore.c:355:9: error: unknown type name ‘EGL_DISPMANX_WINDOW_T’
  355 |         EGL_DISPMANX_WINDOW_T handle;       // Native window handle (graphic device)
      |         ^~~~~~~~~~~~~~~~~~~~~
/home/pi/raylib-master/src/rcore.c: In function ‘InitGraphicsDevice’:
/home/pi/raylib-master/src/rcore.c:4381:23: error: request for member ‘element’ in something not a structure or union
 4381 |     CORE.Window.handle.element = dispmanElement;
      |                       ^
/home/pi/raylib-master/src/rcore.c:4382:23: error: request for member ‘width’ in something not a structure or union
 4382 |     CORE.Window.handle.width = CORE.Window.render.width;
      |                       ^
/home/pi/raylib-master/src/rcore.c:4383:23: error: request for member ‘height’ in something not a structure or union
 4383 |     CORE.Window.handle.height = CORE.Window.render.height;
      |                       ^
/home/pi/raylib-master/src/rcore.c:4386:90: warning: passing argument 3 of ‘eglCreateWindowSurface’ makes integer from pointer without a cast [-Wint-conversion]
 4386 | Window.surface = eglCreateWindowSurface(CORE.Window.device, CORE.Window.config, &CORE.Window.handle, NULL);
      |                                                                                 ^~~~~~~~~~~~~~~~~~~
      |                                                                                 |
      |                                                                                 int *

In file included from /home/pi/raylib-master/src/rcore.c:254:
/usr/include/EGL/egl.h:155:109: note: expected ‘EGLNativeWindowType’ {aka ‘long unsigned int’} but argument is of type ‘int *’
  155 | Y eglCreateWindowSurface (EGLDisplay dpy, EGLConfig config, EGLNativeWindowType win, const EGLint *attrib_list);
      |                                                             ~~~~~~~~~~~~~~~~~~~~^~~

make[2]: *** [raylib/CMakeFiles/raylib.dir/build.make:82: raylib/CMakeFiles/raylib.dir/rcore.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:374: raylib/CMakeFiles/raylib.dir/all] Error 2
make: *** [Makefile:182: all] Error 2
```

### Environment

My linux platform:
```
pi@raspberrypi:~/raylib-master $ uname -a
Linux raspberrypi 5.10.63+ #1488 Thu Nov 18 16:14:04 GMT 2021 armv6l GNU/Linux
```
I configured cmake with the following command:
```
cmake . -DPLATFORM="Raspberry Pi"
```

**Comment by raysan5** [comment] 2021-12-01 21:13
@pekdemir A couple of weeks ago it worked perfectly for me. Could you try with:
```
make PLATFORM=PLATFORM_RPI -B
```

**Comment by pekdemir** [comment] 2021-12-01 21:30
Tried with above command and it failed again. I have no X11 system. I only installed libgles2-mesa-dev. Might this be the problem?

**Comment by raysan5** [comment] 2021-12-01 22:08
@pekdemir Actually on RPIZeroW `libgles2-mesa-dev` shouldn't be required for `PLATFORM_RPI` native mode.

**Comment by julianbcampbell** [comment] 2021-12-02 18:04
I had exactly the same problem compiling raylib on a Pi Zero and Pi 3. Running on Raspberry Pi OS lite (bullseye)

Initially on compiling I get the error shown in the attached file, which is that the compiler can't find the <GLES2/g12.h> file to include. 
![Raylib Compile 1](https://user-images.githubusercontent.com/60845634/144477656-01c47050-8d67-4305-b95a-01c2b6076b7c.jpg)

If I install libgles2-mesa-dev I get the error as shown above. Running on Raspberry Pi OS lite (bullseye)

**Comment by colesnicov** [comment] 2021-12-03 23:14
I too on RPI 2 B. OS Lite (bullseye)

**Comment by raysan5** [comment] 2021-12-11 10:59
On Raspberry Pi OS Bullseye KMS is used as default display driver and it seems dispmanx support could have been removed. So, on Raspberry Pi OS Bullseye, native RPI support with `PLATFORM_RPI` is not working anymore.

@pekdemir @julianbcampbell @colesnicov You should build raylib with `PLATFORM_DRM` for native RPI support.

**Comment by julianbcampbell** [comment] 2021-12-11 11:31
Raspberry Pi Foundation have launched a legacy version of Raspberry Pi OS, which is based on Debian Buster. I tried this and it works fine on Raspberry Pi 3, building with PLATFORM_RPI compiles and runs perfectly in native mode! I suspect Pi Zero will also work although I haven't tried it yet.

Raylib is fantastic software btw!

**Comment by colesnicov** [comment] 2021-12-13 18:11
Hi, So I managed to compile a library for RPI2 according to this post, but it still doesn't work.

Os: RapiOS (Buster)
RPI 2 Model B
GL Driver: FULL_KMS

I'm getting this mistake:

```
~ ./core_basic_window 
~INFO: Initializing raylib 4.0
~INFO: Supported raylib modules:
~INFO:     > rcore:..... loaded (mandatory)
~INFO:     > rlgl:...... loaded (mandatory)
~INFO:     > rshapes:... loaded (optional)
~INFO:     > rtextures:. loaded (optional)
~INFO:     > rtext:..... loaded (optional)
~INFO:     > rmodels:... loaded (optional)
~INFO:     > raudio:.... loaded (optional)
* failed to add service - already in use?
```

**Comment by pekdemir** [comment] 2021-12-14 18:42
Hi again, I tried to build using `PLATFORM_DRM` on my Zero, and it compiled raylib and examples successfully! I had to install `libdrm-dev` and `libgbm-dev` before compiling. I also enabled Full KMS option in `raspi-config`. However, when I try to run core_basic_window, I get following errors:
```
INFO: Initializing raylib 4.0
INFO: DISPLAY: No graphic card set, trying platform-gpu-card
INFO: DISPLAY: Failed to open platform-gpu-card, trying card1
INFO: DISPLAY: Failed to open graphic card1, trying card0
WARNING: DISPLAY: Failed to open graphic card
FATAL: Failed to initialize Graphic Device
 ```

**Comment by colesnicov** [comment] 2021-12-14 19:17
It seems that the problem is that I do not have a display manager installed. When I try to run the example rectangle.c from [here](https://jan.newmarch.name/LinuxSound/Diversions/RaspberryPiOpenGL/), I get the same error:

```
pi@raspberrypi:~/dev $ ./rectangle 
* failed to add service - already in use?
```

 and now I'm at the end. I don't know much about the display manager.

**Comment by colesnicov** [comment] 2021-12-14 19:21
@pekdemir 
> Hi again, I tried to build using `PLATFORM_DRM` on my Zero, and it compiled raylib and examples successfully! 

I think Zero does not support  PLATFORM_DRM?

**Comment by pekdemir** [comment] 2021-12-14 19:35
@colesnicov Have you tried disabling FULL_KMS and switching to LEGACY GL driver for your problem?
sudo raspi-config -> Advanced Options -> GL Driver -> Select Legacy.

**Comment by pekdemir** [comment] 2021-12-14 20:27
Finally, I am able to run examples on my Zero! I need to connect HDMI to my monitor and it works on that one :thinking: My drm driver was assigned on fb0 which is HDMI output of device. 
```
vc4-drm soc:gpu: [drm] fb0: vc4drmfb frame buffer device
```

So, for the next step, I will try to assign drm to my spi lcd on fb1. 

Thanks for the support

**Comment by colesnicov** [comment] 2021-12-14 23:12
> Finally, I am able to run examples on my Zero! I need to connect HDMI to my monitor and it works on that one thinking My drm driver was assigned on fb0 which is HDMI output of device.
> 
> ```
> vc4-drm soc:gpu: [drm] fb0: vc4drmfb frame buffer device
> ```
> 
> So, for the next step, I will try to assign drm to my spi lcd on fb1.
> 
> Thanks for the support

Productivity? what is your FPS?

**Comment by raysan5** [comment] 2021-12-15 11:43
@colesnicov Rasberry Pi Zero should support `PLATFORM_DRM` if using RPI OS Bullseye version, with the RPI OS Legacy (Buster) it should still work with `PLATFORM_RPI`. Depending on the RPI OS, a specific KMS driver configuration is required to work in native mode.

@pekdemir Could we close this issue?

**Comment by pekdemir** [comment] 2021-12-15 16:28
I think we can close it. For the closing note here: My build problem is solved by using `PLATFORM_DRM` build option on RPI OS Bullseye. 

@raysan5 May be another issue should be opened to deal with `PLATFORM_RPI` option on new RPI OS. I leave this one up to you ;) Thanks.

**Comment by raysan5** [comment] 2021-12-15 17:08
@pekdemir `PLATFORM_RPI` should work with RPI OS Legacy (Buster).

**Closed by raysan5** 2021-12-15 17:08 UTC
Labels: raspberrypi

**Comment by colesnicov** [comment] 2021-12-29 01:53
> @colesnicov Have you tried disabling FULL_KMS and switching to LEGACY GL driver for your problem? sudo raspi-config -> Advanced Options -> GL Driver -> Select Legacy.

When I do switch from FULL KMS to LEGACY, I will did lost the content from core folder '/opt/vc'...
