### ISSUE TITLE
[rlgl] `rlNormal3f()` provided normals not stored internally

### ISSUE THREAD

**Issue by DeexCoding** [raysan5/raylib#2898] opened 2023-01-28 09:51 UTC
I have noticed that raylib doesn't send my normals to the vertexNormal attribute in the shader even tough I and the default raylib functions for DrawSphere etc. send it too.

**Comment by raysan5** [comment] 2023-01-28 11:20
@DeexCoding I'm afraid that's the expected behaviour as it is designed now, batching system using `rlVertexBuffer` data type does not store normals.

That decision was taken for simplification and performance, considering most users do not need to provide the normals manually beside the normal calculated considering triangles order definition (counter-clock-wise).

What it is the specific use case for them?

If you are defining custom meshes I recommend using the `Mesh` structure that supports normals, tangents and more.

**Comment by DeexCoding** [comment] 2023-01-28 11:52
The specific case is that I have a DrawTexturePro3D which is the exact same as DrawTexturePro, but with 3d paramaters. It's like pixel art stuff rendered sort of like cards. I would really like to have some lighting and shadows in the artstyle. (Btw I saw the TODO for storing normals lol) I could send some screenshots if you still don't understand the artstyle I'm going for.

**Comment by raysan5** [comment] 2023-01-28 12:33
@DeexCoding I think you can use a `Mesh` for the cards instead of `DrawTexturePro3D()`, did you consider that option?

 > If I've understood the code you have different vbos for colors, positions, texcoords, so I don't really understand why it'd be so hard to implement normals.

No hard at all but it requires extra memory, extra maths and extra shader processing because of normals and most users won't require it ever.

**Comment by raysan5** [comment] 2023-01-30 16:09
I'm closing this issue as design.

**Closed by raysan5** 2023-01-30 16:09 UTC
