### ISSUE TITLE
[core] F12 key completely freezes game

### ISSUE THREAD

**Issue by HeCorr** [raysan5/raylib#2239] opened 2021-12-22 22:56 UTC
- [ ] I tested it on latest raylib version from master branch
 - [x] I checked there is no similar issue already reported
 - [x] My code has no errors or misuse of raylib

### Issue description

On Windows, when the F12 key is pressed, the game completely freezes.
You can't press ESC, can't close the window, Alt + F4 and Win + D don't do anything.
If the game is in full screen the only thing you can do is to reboot your computer as you can't even see/interact with the task manager.

### Environment

Windows 10 64bit. I don't know anything else, I just downloaded the 4.0.0 release from GitHub.
I believe I have TDM-GCC installed. (if I search for "mingw" or "cygwin" they both appear but TDM-GCC is what shows up in the installed programs list.)
My GPU is a 1050 Ti.

### Issue Screenshot

No screenshot.

### Code Example

```c
#include "raylib.h"

int main(void)
{
    InitWindow(600, 400, "title");
    SetTargetFPS(60);
    while (!WindowShouldClose())
    {
        BeginDrawing();
        ClearBackground(WHITE);
        EndDrawing();
    }
    CloseWindow();
    return 0;
}
```

**Comment by raysan5** [comment] 2021-12-23 10:17
@HeCorr That's very weird, never had that issue. Unfortunately I can not reproduce with the provided code. 

I need more info about your system: OS, CPU, GPU. Did you install latest drivers for your graphics card?

You should try disabling `SUPPORT_SCREEN_CAPTURE` and `SUPPORT_GIF_RECORDING` on `raylib/src/config.h` and recompile raylib and try it again. Maybe the issue is the take screenshot feature.

**Comment by HeCorr** [comment] 2021-12-23 15:25
I didn't want to compile it myself so I downloaded the .a file from the releases, but I guess I have to do it after all.

My specs are:
AMD Ryzen 3700x
GTX 1050Ti 4GB
Windows 10 Pro (don't remember the build. but it's not the latest)

I'll also try updating the drivers and see if that fixes the issue. Thanks

**Comment by HeCorr** [comment] 2021-12-24 18:40
An interesting update.. I just built Raylib from master branch with both options disabled in config.h and the issue still occurs.

![image](https://user-images.githubusercontent.com/75134774/147368992-c4a25668-820f-4525-bae3-d1d842bff2db.png)

Still haven't updated my drivers, that comes next.. but I need this game finished by tomorrow so I'll be doing that later.

**Comment by raysan5** [comment] 2021-12-24 18:50
@HeCorr In that case I'm afraid it's not a raylib issue itself because if those options are disabled F12 does absolutely nothing from raylib side. It could be related to your GPU, do you have installed some kind of `NVIDIA Experience` software to record gameplays? Could you try disabling it? What happens when pressing F12 running other OpenGL games? Let's see if the drivers update correct the issue.

**Comment by HeCorr** [comment] 2021-12-24 19:37
> do you have installed some kind of NVIDIA Experience software to record gameplays?

Not that I'm aware of. I use OBS studio for capturing and my recording shortcuts are different.

> What happens when pressing F12 running other OpenGL games?

I don't have any I can test with so I don't know.

**Comment by raysan5** [comment] 2021-12-28 11:45
It seems this issue is user-specific, probably related to drivers or some other installed program conflict. I'm closing this issue.

**Closed by raysan5** 2021-12-28 11:45 UTC
