### ISSUE TITLE
Display on Retina device occupies lower-left quad of screen

### ISSUE THREAD

**Issue by jamiltron** [raysan5/raylib#168] opened 2016-07-31 20:03 UTC
When opening a window of 800x600 on a retina Macbook pro, raylib outputs that the render & screen size as being 800x600, but rendering only happens in the lower left section of the screen.

This is probably due to pixels and screen coordinates not being 1:1 on a retina display. See [section 4.3 of the glfw faq](http://www.glfw.org/faq.html#why-is-my-output-in-the-lower-left-corner-of-the-window).

Any work-around for this?

**Comment by raysan5** [comment] 2016-07-31 20:15
Hi @jamiltron,

Have you tried raylib [latest develop branch](https://github.com/raysan5/raylib/tree/develop)?

Supposedly, this issue was corrected with commit https://github.com/raysan5/raylib/commit/a422e394925e68ab687ef70527c3e207234d8bd7 some days ago. It was related to issue https://github.com/raysan5/raylib/issues/157.

Not integrated into master branch yet.

Please, let me know if it works for you using develop branch. :)

**Comment by jamiltron** [comment] 2016-07-31 20:38
I checked out the develop branch, and I tried including/linking with the release/osx directory, but am still running into the same issue.

When I try building the source (mkdir build; cd build; cmake ..; make)

I get 3 errors:

```
/Users/jamiltron/opt/raylib/src/audio.c:838:9: error: non-void function
      'LoadMusicBufferStream' should return a value [-Wreturn-type]
        return; // error
        ^
/Users/jamiltron/opt/raylib/src/audio.c:845:80: error: non-void function
      'LoadMusicBufferStream' should return a value [-Wreturn-type]
  ...|| musicStreams[buffer.index].xmctx) return; // error
                                          ^
/Users/jamiltron/opt/audio.c:992:6: error: conflicting types for
      'StopMusicStreamEx'
void StopMusicStreamEx(int index)
     ^
```

**Comment by raysan5** [comment] 2016-07-31 21:04
Including/linking with release/osx does not work, raylib should be recompiled (build the source again).

Thanks for pointing the issue with audio, just updated that file a couple of days ago and now I'm redesigning the module (Issue https://github.com/raysan5/raylib/issues/144). Probably by tomorrow it will be ready and, hopefully, this issue solved.

**Comment by jamiltron** [comment] 2016-07-31 22:16
Thank you!

**Comment by raysan5** [comment] 2016-08-01 11:02
Hi @jamiltron, just updated develop branch, please, could you try it again? Remember you need to recompile raylib source to make surelibrary is updated (verify creation date of `libraylib.a` once generated). Thanks!

**Comment by jamiltron** [comment] 2016-08-02 04:55
That fixed the issue, thank you very much!

**Comment by chances** [comment] 2020-10-04 09:44
@raysan5 I'm experiencing this issue _after_ I resize my app's window in macOS Catalina 10.15

**Comment by iostapyshyn** [comment] 2020-12-26 12:51
@raysan5 I experience the same issue just after creating the window with raylib 3.5.0. Strangely enough moving the window around a bit fixes it immediately.

**Comment by raysan5** [comment] 2020-12-26 13:00
@iostapyshyn yeah, it seems GLFW framebuffer resize callback is called when moving the Window and it solves the issue... I'm reopening it for further investigation...

**Comment by funcelot** [comment] 2021-01-04 22:02
> @iostapyshyn yeah, it seems GLFW framebuffer resize callback is called when moving the Window and it solves the issue... I'm reopening it for further investigation...

Just see this, i made a pull request which seems fixes all bugs for windows 10 https://github.com/raysan5/raylib/pull/1512

**Comment by funcelot** [comment] 2021-01-04 22:04
> @raysan5 I experience the same issue just after creating the window with raylib 3.5.0. Strangely enough moving the window around a bit fixes it immediately.

can you test my pull request, i made for windows 10? it all worked! cant believe i did it

**Comment by funcelot** [comment] 2021-01-05 09:37
@jamiltron @raysan5 I will do some tests, on mac os x, and also fullscreen toggle on mac os x on my mac book pro retina mid 2013, PR https://github.com/raysan5/raylib/pull/1512 to see if that will work

**Comment by raysan5** [comment] 2021-01-12 23:38
Duplicate of #1510

**Closed by raysan5** 2021-01-12 23:38 UTC
