### ISSUE TITLE
[models] gltf animation not animating correctly

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1800] opened 2021-05-31 08:24 UTC
here's the model 
[walk.glb.tar.gz](https://github.com/raysan5/raylib/files/6568819/walk.glb.tar.gz)

basically loaded and displayed as per examples/models/models_gltf_animation.c

It looks like the rotations are messed up somehow?

This was originally a download from cgtrader as a blend file which I then exported to gltf, I'm going to relook in blender as it could be just a case of some setting their...

**Comment by chriscamacho** [comment] 2021-05-31 09:21
i also took a walk cycle from mixamo.com exported as dfx and dea without luck :(

**Comment by raysan5** [comment] 2021-05-31 09:46
This issue seems a duplicate of #1799. I'm closing it.

**Closed by raysan5** 2021-05-31 09:46 UTC
