### ISSUE TITLE
[core] Camera3D position at origin invalid

### ISSUE THREAD

**Issue by raywan** [raysan5/raylib#768] opened 2019-02-25 05:00 UTC
I was trying to initialize a camera positioned at the origin, looking down the z-axis. These configurations, from what I understand, should not be a degenerate case. In case I'm misunderstanding the coordinate system, I try to render 6 cubes. Two on each positive/negative part of the axis respectively, so there should be at least one cube rendered onto the screen. However, starting the program only displays the clear color. Furthermore, since the camera mode was set to `CAMERA_FREE`, we should be able to zoom in/out as well as pan. These do not work either. When I translate the camera slightly, however,

```camera.position = (Vector3) { 0.01f, 0.0f, 0.0f }``` things do start working. 

Below are code snippets of camera initialization as well as the relevant part in the main game loop where cubes are rendered. 

```c++
  Camera3D camera;
  camera.position = (Vector3) { 0.0f, 0.0f, 0.0f };
  camera.target = (Vector3){ 0.0f, 0.0f, 1.0f };
  camera.up = (Vector3){ 0.0f, 1.0f, 0.0f };
  camera.fovy = 90.0f;
  camera.type = CAMERA_PERSPECTIVE;

  SetCameraMode(camera, CAMERA_FREE);
```

```c++
    UpdateCamera(&camera);
    BeginDrawing();
      ClearBackground(WHITE);
      BeginMode3D(camera);
        DrawCube((Vector3) {10.0f, 0.0f, 0.0f}, 1.0f, 1.0f, 1.0f, RED);
        DrawCube((Vector3) {0.0f, 10.0f, 0.0f}, 1.0f, 1.0f, 1.0f, BLUE);
        DrawCube((Vector3) {0.0f, 0.0f, 10.0f}, 1.0f, 1.0f, 1.0f, GREEN);

        DrawCube((Vector3) {-10.0f, 0.0f, 0.0f}, 1.0f, 1.0f, 1.0f, PINK);
        DrawCube((Vector3) {0.0f, -10.0f, 0.0f}, 1.0f, 1.0f, 1.0f, ORANGE);
        DrawCube((Vector3) {0.0f, 0.0f, -10.0f}, 1.0f, 1.0f, 1.0f, LIME);

        DrawGrid(100, 1.0f);
      EndMode3D();
    EndDrawing()
```

 **Screenshots**

```camera.position = (Vector3) { 0.0f, 0.0f, 0.0f }```
![screen shot 2019-02-24 at 11 40 18 pm](https://user-images.githubusercontent.com/3066609/53314701-bb929200-388d-11e9-9b93-9af4882cd4a9.png)

```camera.position = (Vector3) { 0.01f, 0.0f, 0.0f }```

![giphy](https://user-images.githubusercontent.com/3066609/53315187-02818700-3890-11e9-8bcb-01e83f3cadd5.gif)

**Comment by raysan5** [comment] 2019-02-25 22:21
@raywan you're right, actually [camera.h](https://github.com/raysan5/raylib/blob/master/src/camera.h) module was designed long time ago and it should be completely reviewed...

**Comment by raywan** [comment] 2019-02-26 15:12
@raysan5 Okay, I wasn't 100% sure whether I made a mistake. Thank you for all your hard work on raylib!

**Comment by raysan5** [comment] 2019-04-23 21:38
I'm afraid this issue will persist as long as EULER math is being used to calculate camera movement. I'll close this issue for now because it will require a redesign of camera module. Sorry for the inconvenience...

**Closed by raysan5** 2019-04-23 21:38 UTC
