### ISSUE TITLE
[rcore] App freezes on Android when losing focus

### ISSUE THREAD

**Issue by xslendix** [raysan5/raylib#3802] opened 2024-02-18 23:04 UTC
Please, before submitting a new issue verify and check:

 - [*] I tested it on latest raylib version from master branch
 - [*] I checked there is no similar issue already reported
 - [*] I checked the documentation on the [wiki](https://github.com/raysan5/raylib/wiki)
 - [*] My code has no errors or misuse of raylib

### Issue description

When losing focus of the game, for example when pressing the home or activities button, when you come back to the application, it freezes.

### Environment

Android 11 MIUI 12.5.8, `NativeActivity` launched from `ComposableActivity` using an Intent.

### Issue Screenshot

Sorry, can't.

### Code Example

Any Raylib application would do, could possibly have something like this:

```cpp
#include <raylib.h>
#include <cmath>

int main(void) {
  InitWindow(1280, 720, "hi");
  while (!WindowShouldClose()) {
    BeginDrawing();
    ClearBackground(BLACK);
    DrawCircleV({20+sin(GetTime()), 20}, 20, RED);
    EndDrawing();
  }
  CloseWindow();
}
```

**Comment by Bigfoot71** [comment] 2024-02-22 03:40
Of all the tests I've done for raylib 5.0 release I haven't seen this problem _(on Android 10)_, nor from people using raymob and there doesn't seem to have been any code changes, regarding Android, since the last release that could affect this.

How do you build your project for Android?

**Comment by xslendix** [comment] 2024-02-22 14:58
@Bigfoot71 I am working on a (currently) proprietary game, I can give you access to source code, but you should not redistribute it or any builds. If you are fine with that then sure.

**Comment by Bigfoot71** [comment] 2024-02-22 15:15
> @Bigfoot71 I am working on a (currently) proprietary game, I can give you access to source code, but you should not redistribute it or any builds. If you are fine with that then sure. I am building from Android Studio.

@xslendix Of course, if you do it, I commit to it publicly here, I will have no interest in it, but you can also try to make a minimalist example that reproduces the issue in order to share it here, other people could also give their opinion on this, if you agree with that. As you wish.

**Comment by xslendix** [comment] 2024-02-22 15:17
@Bigfoot71 cool check discord

**Comment by Bigfoot71** [comment] 2024-02-25 00:17
Not seeing any updates here, I confirm that upon verification, everything is correct on raylib's end and that the issue stemmed from the author's project activity lifecycle management.

@raysan5 The issue can be closed in my opinion.

**Comment by xslendix** [comment] 2024-02-26 06:20
Not yet. I think I am starting the activity properly.

**Comment by Bigfoot71** [comment] 2024-02-26 23:23
@xslendix Tested with release 5.0 and with the current master branch (https://github.com/raysan5/raylib/commit/1fc4f4ac9c539a963d72d3ee0cf2bc6ce72e5b56).

**I confirm that there are no issues with resuming the application on the raylib side.**

You can test it on your device with this: https://github.com/Bigfoot71/raymob/tree/5.1-dev-test

**Comment by Bigfoot71** [comment] 2024-02-26 23:44
@xslendix Tested with release 5.0 and with the current master branch (https://github.com/raysan5/raylib/commit/1fc4f4ac9c539a963d72d3ee0cf2bc6ce72e5b56).

**I confirm that there are no issues with resuming the application on the raylib side.**

You can test it on your device with this: https://github.com/Bigfoot71/raymob/tree/5.1-dev-test

**Comment by raysan5** [comment] 2024-04-21 08:18
Closing this issue, it seems related to configuration on user side.

**Closed by raysan5** 2024-04-21 08:18 UTC
Labels: platform: android
