### ISSUE TITLE
[build] Having issues setting up raylib for MacOS

### ISSUE THREAD

**Issue by TheSuperFastOne** [raysan5/raylib#2866] opened 2023-01-18 01:56 UTC
<img width="225" alt="Screen Shot 2023-01-17 at 8 53 07 PM" src="https://user-images.githubusercontent.com/121529208/213061879-59f52f16-3e2e-495b-bb5b-e987e19bafac.png">

Error message:

clang -x objective-c -c rglfw.c -Wall -D_GNU_SOURCE -DPLATFORM_DESKTOP -DGRAPHICS_API_OPENGL_33 -Wno-missing-braces -Werror=pointer-arith -fno-strict-aliasing  -std=c99 -O1 -Werror=implicit-function-declaration -I. -Iexternal/glfw/include -Iexternal/glfw/deps/mingw
In file included from rglfw.c:61:
In file included from ./external/glfw/src/init.c:30:
In file included from ./external/glfw/src/internal.h:331:
In file included from ./external/glfw/src/platform.h:42:
In file included from ./external/glfw/src/cocoa_platform.h:29:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Carbon.framework/Headers/Carbon.h:28:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/HIToolbox.h:240:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Carbon.framework/Frameworks/HIToolbox.framework/Headers/IMKInputSession.h:23:
In file included from /Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:12:
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSBundle.h:91:143: error: function does not return NSString
- (NSAttributedString *)localizedAttributedStringForKey:(NSString *)key value:(nullable NSString *)value table:(nullable NSString *)tableName NS_FORMAT_ARGUMENT(1) NS_REFINED_FOR_SWIFT API_AVAILABLE(macos(12.0), ios(15.0), watchos(8.0), tvos(15.0));
                                                         ~~~~~~~~~~~~~~                                                                       ^                  ~
/Library/Developer/CommandLineTools/SDKs/MacOSX12.1.sdk/System/Library/Frameworks/Foundation.framework/Headers/NSObjCRuntime.h:103:48: note: expanded from macro 'NS_FORMAT_ARGUMENT'
        #define NS_FORMAT_ARGUMENT(A) __attribute__ ((format_arg(A)))
                                                      ^          ~
1 error generated.
make: *** [rglfw.o] Error 1



Thats it!

Tried add rlgfw.m with just one line:
#include "rlgfw.c"

**Comment by raysan5** [comment] 2023-01-20 15:38
@TheSuperFastOne It seems the issue is related to GLFW library, are you using the provided `raylib/src/Makefile` to build the library?

**Comment by Not-Nik** [comment] 2023-01-21 18:39
Can't reproduce on my MacBook Pro with macOS 13.1, neither on Homebrew's clang 15.0.7 nor Apple clang 14.0.0. Try updating your command line tools at System Settings > General > Software Update.

**Comment by raysan5** [comment] 2023-01-21 18:51
@Not-Nik thanks for the feedback. Closing this issue. If problem persist, please comment to reopen it.

**Closed by raysan5** 2023-01-21 18:51 UTC
Labels: macOS, good first issue
