### ISSUE TITLE
[build] Android APK gets stuck when pressed the back button to exit

### ISSUE THREAD

**Issue by JasonNumberThirteen** [raysan5/raylib#1296] opened 2020-07-02 16:35 UTC
### Issue description

After compiling an APK for Android using example source code (attached below), moving it to my smartphone, installing and launching, everything works properly until I press the "back" key on smartphone to exit application. **It immediately gets stuck after pressing the button**. Having no clues what's wrong with it, I decided to write this here, maybe someone else had this problem. I took a look at examples and games and **I didn't notice any exclusive commands protecting from this issue**. No clear informations about effective solution forced me to report this. Added the orange text to **clearly show that moment when the app becomes "frozen"**.

### Environment

Compilation for Android 10 (**API level 29**) on **Windows 10 64-bit** operating system using "_raylib_" 3.0 from the official installer in "_Visual Studio Code_" IDE. APK launched on **Samsung Galaxy A40** smartphone.

### Issue Screenshot

Snapshot from the smartphone showing popup displayed after a ~1 minute after pressing the "back" button. From Polish language: "_raylibTest isn't responding_". Options are "_Close app_" and "_Wait_".
![androidAPK](https://user-images.githubusercontent.com/40078536/86384374-edd8ae80-bc8e-11ea-9810-26c51f33493b.jpg)

### Source code
```c
#include <raylib.h>
#include <stdbool.h>

#define GAME_WIDTH 256
#define GAME_HEIGHT 144

int main(void)
{
	bool running = true;
	
	InitWindow(GAME_WIDTH, GAME_HEIGHT, "raylibTest");
	SetTargetFPS(60);

	while (!WindowShouldClose() && running)
	{
		BeginDrawing();
		ClearBackground(WHITE);
		DrawRectangle(0, 0, GAME_WIDTH, GAME_HEIGHT, BLACK);

		if(IsKeyDown(KEY_BACK))
		{
			DrawText("EXITING...", 32, 32, 32, ORANGE);
			
			running = false;
		}

		EndDrawing();
	}

	CloseWindow();
	
	return 0;
}
```

**Comment by raysan5** [comment] 2020-07-10 09:42
@JasonNumberThirteen Please could you try:
```c
        while (!WindowShouldClose() && running)
	{
		if (IsKeyPressed(KEY_BACK)) running = false;

		BeginDrawing();
		ClearBackground(WHITE);
		DrawRectangle(0, 0, GAME_WIDTH, GAME_HEIGHT, BLACK);
		EndDrawing();
	}
```

**Comment by JasonNumberThirteen** [comment] 2020-07-10 14:39
@raysan5 Unfortunately, it didn't solve the problem. App is getting stuck just like before.

**Comment by raysan5** [comment] 2020-07-10 17:55
@JasonNumberThirteen Checking the related code, I'm afraid that's the expected behaviour. You're closing the rendering system and consequently application stops. What are you trying to do? Keep in mind that raylib is C and low level, all possible Android states should be manually managed (probably from an upper Java layer).

**Comment by JasonNumberThirteen** [comment] 2020-07-10 19:51
@raysan5 I know that C makes all low level operations available being a high level language and is very portable (that's why I've chosen C) and it might be some issues when trying to port to different platform, but something different is weird for me: Android platform support has some longer time and nobody had this issue before (and no one reported this)? I can't believe it. Even on Discord channel I haven't found any solutions or suggestions how to fix it. I don't want to spend a couple of months to fix one little thing (maybe I'll be forced to just quit and search different tool).

So, I assume that I have to create another blank project in Android Studio and from there try to handle this issue? I was looking also at SDL exporting method to Android and there also is the same problem. Cannot handle this in the same code. I had a hope that I could miss some command, but it seems I must search for solution on my own.

"What are you trying to do?"
Exactly what I wrote: **just exit an application like many applications from Google Play by pressing the back button**. Nothing else (for now). I'm creating a [template for my future games](https://twitter.com/JasonNumberXIII/status/1271741460191350786?s=20) and I wanted to make also export to Android (and later for HTML5). Everything was OK, until I started compilation for Android (a lot of troubles and frustrations, no clear solutions, only some "trails").

Anyway, thanks for response. I have always in mind that you have already a lot of work to do. I hope this might be fixed and none "masterful techniques" will be required to make this perfectly working.

**Comment by raysan5** [comment] 2020-07-14 16:52
@JasonNumberThirteen I reviewed the code and by default back-button interaction is disabled internally, the reason is because if leaving the control to the OS, it closes the graphic context and app needs to be restarted, so, the most appropiate way to manage back-button is from a higher-level Java class, instead of raylib.

So, I'm afraid that it will be up to you to investigate a solution or change to a more high-level engine that could manage that for you.

**Closed by raysan5** 2020-07-14 16:52 UTC
