### ISSUE TITLE
[raudio] No sound since 4.2.0

### ISSUE THREAD

**Issue by cyberic99** [raysan5/raylib#2740] opened 2022-10-03 19:25 UTC
After upgrading to the latest raylib version, my archlinux x86_64 application suddenly stopped making any sound.
(I first encountered the problem using python bindings)

So I tried to compile audio_sound_loading.c example against different raylib versions:

raylib 4.0: sound OK
raylib 4.2: no sound
2e26cf48 (latest master as of now): no sound

I can see the sound source in pavucontrol, and I see no errors in logs, but the application is completely silent.

do you want me to try a git bisect, or can I provide additional debugging info ?

Thank you

**Comment by electronstudio** [comment] 2022-10-03 19:44
i would bisect around https://github.com/raysan5/raylib/commit/22c17da4d7b33f1c3a345b2e04e7935e16603ae9

**Comment by raysan5** [comment] 2022-10-03 20:15
@cyberic99 I just published an update of rFXGen yesterday and audio works as expected. I would need more info to track the issue properly, maybe is Arch Linux specific.

**Comment by cyberic99** [comment] 2022-10-06 19:24
yes... that's it:

```
commit ca12ef48e9e9f4eae03b1ca43ec3eb0a78d63dd3
Author: Ray <raysan5@gmail.com>
Date:   Thu Mar 24 11:44:52 2022 +0100

    Fixes #2408
```
sound OK
```
commit 22c17da4d7b33f1c3a345b2e04e7935e16603ae9
Author: Ray <raysan5@gmail.com>
Date:   Thu Mar 24 18:22:09 2022 +0100

    Update to miniaudio 11.8
```
no sound

**Comment by raysan5** [comment] 2022-10-06 21:18
@cyberic99 It seems the issue could be related to miniaudio? On Windows it works as expected.

**Comment by cyberic99** [comment] 2022-10-06 22:37
I took the latest raylib master, downgraded miniaudio to v0.10.42, and the sound does work correctly...

should I report directly to miniaudio project ?

**Comment by raysan5** [comment] 2022-10-06 22:43
@cyberic99 Thanks for testing, pinging @mackron about it.

**Comment by mackron** [comment] 2022-10-07 07:24
There's not enough information to go on. Need to see some kind of log. Maybe try compiling with the `MA_DEBUG_OUTPUT` define. You could also try replacing miniaudio with the version currently in the dev branch in the miniaudio repository - I've got a few fixes for various things in there which *might* fix this.

**Comment by chriscamacho** [comment] 2022-10-07 15:39
FWIW works just fine on Void Linux (64bit) - with sometimes flaky intel SOF audio chip, cloned a day or so ago...

**Comment by cyberic99** [comment] 2022-10-07 15:54
> There's not enough information to go on. Need to see some kind of log. Maybe try compiling with the MA_DEBUG_OUTPUT define. You could also try replacing miniaudio with the version currently in the dev branch in the miniaudio repository - I've got a few fixes for various things in there which might fix this.

OK I'll do this and report back, thank you

**Comment by cyberic99** [comment] 2022-10-09 20:54
Ok, so updating to miniaudio [4d813cf](https://github.com/mackron/miniaudio/commit/4d813cfe23c28db165cce6785419fee9d2399766) didn't fix the problem.

But I have found a kind of workaround that could help:
I have 2 soundcards, a ``Notepad-12FX Analog Surround 4.0`` and a ``Jabra usb headset``

When I start the audio test with the notepad soundcard selected, I get no sound, and switching the output to 'jabra' in pavucontrol does not help

however, if I set the output to jabra, then close and restart the audio test, I get sound, and I also get sound if I switch the output to notepad afterwards.

Here are the logs with the notepad soundcard selected:

```
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1600 x 1200
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 350
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce GTX 660 Ti/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 470.141.03
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
DEBUG: Failed to initialize WASAPI backend.
DEBUG: Failed to initialize DirectSound backend.
DEBUG: Failed to initialize WinMM backend.
DEBUG: Failed to initialize Core Audio backend.
DEBUG: Failed to initialize sndio backend.
DEBUG: Failed to initialize audio(4) backend.
DEBUG: Failed to initialize OSS backend.
DEBUG: Attempting to initialize PulseAudio backend...
DEBUG: Loading library: libpulse.so
DEBUG: Loading symbol: pa_mainloop_new
DEBUG: Loading symbol: pa_mainloop_free
DEBUG: Loading symbol: pa_mainloop_quit
DEBUG: Loading symbol: pa_mainloop_get_api
DEBUG: Loading symbol: pa_mainloop_iterate
DEBUG: Loading symbol: pa_mainloop_wakeup
DEBUG: Loading symbol: pa_threaded_mainloop_new
DEBUG: Loading symbol: pa_threaded_mainloop_free
DEBUG: Loading symbol: pa_threaded_mainloop_start
DEBUG: Loading symbol: pa_threaded_mainloop_stop
DEBUG: Loading symbol: pa_threaded_mainloop_lock
DEBUG: Loading symbol: pa_threaded_mainloop_unlock
DEBUG: Loading symbol: pa_threaded_mainloop_wait
DEBUG: Loading symbol: pa_threaded_mainloop_signal
DEBUG: Loading symbol: pa_threaded_mainloop_accept
DEBUG: Loading symbol: pa_threaded_mainloop_get_retval
DEBUG: Loading symbol: pa_threaded_mainloop_get_api
DEBUG: Loading symbol: pa_threaded_mainloop_in_thread
DEBUG: Loading symbol: pa_threaded_mainloop_set_name
DEBUG: Loading symbol: pa_context_new
DEBUG: Loading symbol: pa_context_unref
DEBUG: Loading symbol: pa_context_connect
DEBUG: Loading symbol: pa_context_disconnect
DEBUG: Loading symbol: pa_context_set_state_callback
DEBUG: Loading symbol: pa_context_get_state
DEBUG: Loading symbol: pa_context_get_sink_info_list
DEBUG: Loading symbol: pa_context_get_source_info_list
DEBUG: Loading symbol: pa_context_get_sink_info_by_name
DEBUG: Loading symbol: pa_context_get_source_info_by_name
DEBUG: Loading symbol: pa_operation_unref
DEBUG: Loading symbol: pa_operation_get_state
DEBUG: Loading symbol: pa_channel_map_init_extend
DEBUG: Loading symbol: pa_channel_map_valid
DEBUG: Loading symbol: pa_channel_map_compatible
DEBUG: Loading symbol: pa_stream_new
DEBUG: Loading symbol: pa_stream_unref
DEBUG: Loading symbol: pa_stream_connect_playback
DEBUG: Loading symbol: pa_stream_connect_record
DEBUG: Loading symbol: pa_stream_disconnect
DEBUG: Loading symbol: pa_stream_get_state
DEBUG: Loading symbol: pa_stream_get_sample_spec
DEBUG: Loading symbol: pa_stream_get_channel_map
DEBUG: Loading symbol: pa_stream_get_buffer_attr
DEBUG: Loading symbol: pa_stream_set_buffer_attr
DEBUG: Loading symbol: pa_stream_get_device_name
DEBUG: Loading symbol: pa_stream_set_write_callback
DEBUG: Loading symbol: pa_stream_set_read_callback
DEBUG: Loading symbol: pa_stream_set_suspended_callback
DEBUG: Loading symbol: pa_stream_set_moved_callback
DEBUG: Loading symbol: pa_stream_is_suspended
DEBUG: Loading symbol: pa_stream_flush
DEBUG: Loading symbol: pa_stream_drain
DEBUG: Loading symbol: pa_stream_is_corked
DEBUG: Loading symbol: pa_stream_cork
DEBUG: Loading symbol: pa_stream_trigger
DEBUG: Loading symbol: pa_stream_begin_write
DEBUG: Loading symbol: pa_stream_write
DEBUG: Loading symbol: pa_stream_peek
DEBUG: Loading symbol: pa_stream_drop
DEBUG: Loading symbol: pa_stream_writable_size
DEBUG: Loading symbol: pa_stream_readable_size
DEBUG: System Architecture:
DEBUG:   Endian: LE
DEBUG:   SSE2:   YES
DEBUG:   AVX2:   NO
DEBUG:   NEON:   NO
INFO: [PulseAudio] Playback attr: maxlength=26448, tlength=8816, prebuf=-1, minreq=-1, fragsize=8816; periodSizeInFrames=1102
INFO: [PulseAudio] Playback sample spec: format=16-bit Signed Integer, channels=4, rate=44100
INFO: [PulseAudio] Playback actual attr: maxlength=26448, tlength=6608, prebuf=4416, minreq=2200, fragsize=8816; internalPeriodSizeInFrames=826
INFO: [PulseAudio]
INFO:   Notepad-12FX Analog Surround 4.0 (Playback)
INFO:     Format:      32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO:     Channels:    2 -> 4
INFO:     Sample Rate: 44100 -> 44100
INFO:     Buffer Size: 826*4 (3304)
INFO:     Conversion:
INFO:       Pre Format Conversion:  YES
INFO:       Post Format Conversion: NO
INFO:       Channel Routing:        YES
INFO:       Resampling:             NO
INFO:       Passthrough:            NO
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / PulseAudio
INFO:     > Format:        32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO:     > Channels:      2 -> 4
INFO:     > Sample rate:   44100 -> 44100
INFO:     > Periods size:  3304
INFO: FILEIO: [resources/sound.wav] File loaded successfully
INFO: WAVE: Data loaded successfully (44100 Hz, 16 bit, 1 channels)
INFO: FILEIO: [resources/target.ogg] File loaded successfully
INFO: WAVE: Data loaded successfully (22050 Hz, 16 bit, 2 channels)
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

and with 'jabra' selected:
```
INFO: Initializing raylib 4.2
INFO: Supported raylib modules:
INFO:     > rcore:..... loaded (mandatory)
INFO:     > rlgl:...... loaded (mandatory)
INFO:     > rshapes:... loaded (optional)
INFO:     > rtextures:. loaded (optional)
INFO:     > rtext:..... loaded (optional)
INFO:     > rmodels:... loaded (optional)
INFO:     > raudio:.... loaded (optional)
INFO: DISPLAY: Device initialized successfully
INFO:     > Display size: 1600 x 1200
INFO:     > Screen size:  800 x 450
INFO:     > Render size:  800 x 450
INFO:     > Viewport offsets: 0, 0
INFO: GLAD: OpenGL extensions loaded successfully
INFO: GL: Supported extensions count: 350
INFO: GL: OpenGL device information:
INFO:     > Vendor:   NVIDIA Corporation
INFO:     > Renderer: NVIDIA GeForce GTX 660 Ti/PCIe/SSE2
INFO:     > Version:  3.3.0 NVIDIA 470.141.03
INFO:     > GLSL:     3.30 NVIDIA via Cg compiler
INFO: GL: VAO extension detected, VAO functions loaded successfully
INFO: GL: NPOT textures extension detected, full NPOT textures supported
INFO: GL: DXT compressed textures supported
INFO: GL: ETC2/EAC compressed textures supported
INFO: TEXTURE: [ID 1] Texture loaded successfully (1x1 | R8G8B8A8 | 1 mipmaps)
INFO: TEXTURE: [ID 1] Default texture loaded successfully
INFO: SHADER: [ID 1] Vertex shader compiled successfully
INFO: SHADER: [ID 2] Fragment shader compiled successfully
INFO: SHADER: [ID 3] Program shader loaded successfully
INFO: SHADER: [ID 3] Default shader loaded successfully
INFO: RLGL: Render batch vertex buffers loaded successfully in RAM (CPU)
INFO: RLGL: Render batch vertex buffers loaded successfully in VRAM (GPU)
INFO: RLGL: Default OpenGL state initialized successfully
INFO: TEXTURE: [ID 2] Texture loaded successfully (128x128 | GRAY_ALPHA | 1 mipmaps)
INFO: FONT: Default font loaded successfully (224 glyphs)
DEBUG: Failed to initialize WASAPI backend.
DEBUG: Failed to initialize DirectSound backend.
DEBUG: Failed to initialize WinMM backend.
DEBUG: Failed to initialize Core Audio backend.
DEBUG: Failed to initialize sndio backend.
DEBUG: Failed to initialize audio(4) backend.
DEBUG: Failed to initialize OSS backend.
DEBUG: Attempting to initialize PulseAudio backend...
DEBUG: Loading library: libpulse.so
DEBUG: Loading symbol: pa_mainloop_new
DEBUG: Loading symbol: pa_mainloop_free
DEBUG: Loading symbol: pa_mainloop_quit
DEBUG: Loading symbol: pa_mainloop_get_api
DEBUG: Loading symbol: pa_mainloop_iterate
DEBUG: Loading symbol: pa_mainloop_wakeup
DEBUG: Loading symbol: pa_threaded_mainloop_new
DEBUG: Loading symbol: pa_threaded_mainloop_free
DEBUG: Loading symbol: pa_threaded_mainloop_start
DEBUG: Loading symbol: pa_threaded_mainloop_stop
DEBUG: Loading symbol: pa_threaded_mainloop_lock
DEBUG: Loading symbol: pa_threaded_mainloop_unlock
DEBUG: Loading symbol: pa_threaded_mainloop_wait
DEBUG: Loading symbol: pa_threaded_mainloop_signal
DEBUG: Loading symbol: pa_threaded_mainloop_accept
DEBUG: Loading symbol: pa_threaded_mainloop_get_retval
DEBUG: Loading symbol: pa_threaded_mainloop_get_api
DEBUG: Loading symbol: pa_threaded_mainloop_in_thread
DEBUG: Loading symbol: pa_threaded_mainloop_set_name
DEBUG: Loading symbol: pa_context_new
DEBUG: Loading symbol: pa_context_unref
DEBUG: Loading symbol: pa_context_connect
DEBUG: Loading symbol: pa_context_disconnect
DEBUG: Loading symbol: pa_context_set_state_callback
DEBUG: Loading symbol: pa_context_get_state
DEBUG: Loading symbol: pa_context_get_sink_info_list
DEBUG: Loading symbol: pa_context_get_source_info_list
DEBUG: Loading symbol: pa_context_get_sink_info_by_name
DEBUG: Loading symbol: pa_context_get_source_info_by_name
DEBUG: Loading symbol: pa_operation_unref
DEBUG: Loading symbol: pa_operation_get_state
DEBUG: Loading symbol: pa_channel_map_init_extend
DEBUG: Loading symbol: pa_channel_map_valid
DEBUG: Loading symbol: pa_channel_map_compatible
DEBUG: Loading symbol: pa_stream_new
DEBUG: Loading symbol: pa_stream_unref
DEBUG: Loading symbol: pa_stream_connect_playback
DEBUG: Loading symbol: pa_stream_connect_record
DEBUG: Loading symbol: pa_stream_disconnect
DEBUG: Loading symbol: pa_stream_get_state
DEBUG: Loading symbol: pa_stream_get_sample_spec
DEBUG: Loading symbol: pa_stream_get_channel_map
DEBUG: Loading symbol: pa_stream_get_buffer_attr
DEBUG: Loading symbol: pa_stream_set_buffer_attr
DEBUG: Loading symbol: pa_stream_get_device_name
DEBUG: Loading symbol: pa_stream_set_write_callback
DEBUG: Loading symbol: pa_stream_set_read_callback
DEBUG: Loading symbol: pa_stream_set_suspended_callback
DEBUG: Loading symbol: pa_stream_set_moved_callback
DEBUG: Loading symbol: pa_stream_is_suspended
DEBUG: Loading symbol: pa_stream_flush
DEBUG: Loading symbol: pa_stream_drain
DEBUG: Loading symbol: pa_stream_is_corked
DEBUG: Loading symbol: pa_stream_cork
DEBUG: Loading symbol: pa_stream_trigger
DEBUG: Loading symbol: pa_stream_begin_write
DEBUG: Loading symbol: pa_stream_write
DEBUG: Loading symbol: pa_stream_peek
DEBUG: Loading symbol: pa_stream_drop
DEBUG: Loading symbol: pa_stream_writable_size
DEBUG: Loading symbol: pa_stream_readable_size
DEBUG: System Architecture:
DEBUG:   Endian: LE
DEBUG:   SSE2:   YES
DEBUG:   AVX2:   NO
DEBUG:   NEON:   NO
INFO: [PulseAudio] Playback attr: maxlength=26448, tlength=8816, prebuf=-1, minreq=-1, fragsize=8816; periodSizeInFrames=1102
INFO: [PulseAudio] Playback sample spec: format=16-bit Signed Integer, channels=2, rate=44100
INFO: [PulseAudio] Playback actual attr: maxlength=26448, tlength=6616, prebuf=4416, minreq=2204, fragsize=8816; internalPeriodSizeInFrames=2204
INFO: [PulseAudio]
INFO:   Notepad-12FX Analog Surround 4.0 (Playback)
INFO:     Format:      32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO:     Channels:    2 -> 2
INFO:     Sample Rate: 44100 -> 44100
INFO:     Buffer Size: 2204*3 (6612)
INFO:     Conversion:
INFO:       Pre Format Conversion:  NO
INFO:       Post Format Conversion: YES
INFO:       Channel Routing:        NO
INFO:       Resampling:             NO
INFO:       Passthrough:            NO
INFO: AUDIO: Device initialized successfully
INFO:     > Backend:       miniaudio / PulseAudio
INFO:     > Format:        32-bit IEEE Floating Point -> 16-bit Signed Integer
INFO:     > Channels:      2 -> 2
INFO:     > Sample rate:   44100 -> 44100
INFO:     > Periods size:  6612
INFO: FILEIO: [resources/sound.wav] File loaded successfully
INFO: WAVE: Data loaded successfully (44100 Hz, 16 bit, 1 channels)
INFO: FILEIO: [resources/target.ogg] File loaded successfully
INFO: WAVE: Data loaded successfully (22050 Hz, 16 bit, 2 channels)
INFO: TIMER: Target time per frame: 16.667 milliseconds
```

@mackron I can open a separate issue in miniaudio repo if you like

Thanks for your help

**Comment by raysan5** [comment] 2022-10-09 21:48
@cyberic99 Thanks for testing and the detailed report! Hopefully this issue could be addressed with provided info! :)

**Comment by cyberic99** [comment] 2022-10-10 09:34
Glad I could help.

If you need more info please let me know, at least I have something reproducible with my specific setup

**Comment by raysan5** [comment] 2022-10-12 08:19
@cyberic99 Could you try reverting to previous miniaudio version, the one that worked as expected, but using current raylib master branch. Just to make sure the issue is on miniaudio side, so this issue could be moved to miniaudio repo.

**Comment by raysan5** [comment] 2022-10-15 13:18
It seems this issue is out of scope of raylib.

**Closed by raysan5** 2022-10-15 13:18 UTC

**Comment by cyberic99** [comment] 2022-10-18 21:09
OK so I downgraded miniaudio to v0.10.42, with raylib master, and it works.

So it seems to be a regression in miniaudio between v0.10.42 and v11.8

@mackron do you want me to open an issue in miniaudio repo ?

Thank you

**Comment by mackron** [comment] 2022-10-18 22:03
Feel free to create an issue in the miniaudio project.

**Comment by orcmid** [comment] 2022-10-20 04:41
@cyberic99 The 0.11.10 release of miniaudio was just released.  You should retest with that `external/minaudio.h` to determine whether your problem has been solved.  I will also check on the `#stdalign.h` problem of #2762.

**Comment by cyberic99** [comment] 2022-10-25 22:44
Thanks @orcmid , you were right !
commit d5cd5ebd80ad02a3a9129ecf080007fce7efe4d6
(ie updating from miniaudio v0.11.9 to v0.11.11)
fixes my issue

Thanks !
