### ISSUE TITLE
[models] malloc(): invalid size (unsorted) in OBJ loader

### ISSUE THREAD

**Issue by chriscamacho** [raysan5/raylib#1425] opened 2020-11-03 15:38 UTC
[rocket.zip](https://github.com/raysan5/raylib/files/5482317/rocket.zip)

this small obj used to load into raylib.... but not it fails to load, for the life of me I just can't see it at the moment!

**Comment by raysan5** [comment] 2020-11-03 18:27
This issue seems a duplicate of #1426

**Closed by raysan5** 2020-11-03 18:27 UTC
